-- Automatically generated file: Job Traits

return {
    [1] = {id=1,en="Accuracy Bonus",ja="物理命中率アップ",element=4,icon_id=44,range=0,targets=0},
    [2] = {id=2,en="Evasion Bonus",ja="物理回避率アップ",element=2,icon_id=42,range=0,targets=0},
    [3] = {id=3,en="Attack Bonus",ja="物理攻撃力アップ",element=0,icon_id=40,range=0,targets=0},
    [4] = {id=4,en="Defense Bonus",ja="物理防御力アップ",element=3,icon_id=43,range=0,targets=0},
    [5] = {id=5,en="Magic Atk. Bonus",ja="魔法攻撃力アップ",element=6,icon_id=46,range=0,targets=0},
    [6] = {id=6,en="Magic Def. Bonus",ja="魔法防御力アップ",element=6,icon_id=46,range=0,targets=0},
    [7] = {id=7,en="Max HP Boost",ja="HPmaxアップ",element=6,icon_id=46,range=0,targets=0},
    [8] = {id=8,en="Max MP Boost",ja="MPmaxアップ",element=6,icon_id=46,range=0,targets=0},
    [9] = {id=9,en="Auto Regen",ja="オートリジェネ",element=6,icon_id=46,range=0,targets=0},
    [10] = {id=10,en="Auto Refresh",ja="オートリフレシュ",element=6,icon_id=46,range=0,targets=0},
    [11] = {id=11,en="Rapid Shot",ja="ラピッドショット",element=2,icon_id=42,range=0,targets=0},
    [12] = {id=12,en="Fast Cast",ja="ファストキャスト",element=6,icon_id=46,range=0,targets=0},
    [13] = {id=13,en="Conserve MP",ja="コンサーブMP",element=6,icon_id=46,range=0,targets=0},
    [14] = {id=14,en="Store TP",ja="ストアTP",element=6,icon_id=46,range=0,targets=0},
    [15] = {id=15,en="Double Attack",ja="ダブルアタック",element=6,icon_id=46,range=0,targets=0},
    [16] = {id=16,en="Triple Attack",ja="トリプルアタック",element=6,icon_id=46,range=0,targets=0},
    [17] = {id=17,en="Counter",ja="カウンター",element=6,icon_id=46,range=0,targets=0},
    [18] = {id=18,en="Dual Wield",ja="二刀流",element=6,icon_id=46,range=0,targets=0},
    [19] = {id=19,en="Treasure Hunter",ja="トレジャーハンター",element=6,icon_id=46,range=0,targets=0},
    [20] = {id=20,en="Gilfinder",ja="ギルスティール",element=6,icon_id=46,range=0,targets=0},
    [21] = {id=21,en="Alertness",ja="警戒",element=6,icon_id=46,range=0,targets=0},
    [22] = {id=22,en="Stealth",ja="ステルス",element=6,icon_id=46,range=0,targets=0},
    [23] = {id=23,en="Martial Arts",ja="マーシャルアーツ",element=2,icon_id=42,range=0,targets=0},
    [24] = {id=24,en="Clear Mind",ja="クリアマインド",element=1,icon_id=41,range=0,targets=0},
    [25] = {id=25,en="Shield Mastery",ja="シールドマスタリー",element=6,icon_id=46,range=0,targets=0},
    [32] = {id=32,en="Beast Killer",ja="ビーストキラー",element=6,icon_id=46,range=0,targets=0},
    [33] = {id=33,en="Plantoid Killer",ja="プラントイドキラー",element=6,icon_id=46,range=0,targets=0},
    [34] = {id=34,en="Vermin Killer",ja="ヴァーミンキラー",element=6,icon_id=46,range=0,targets=0},
    [35] = {id=35,en="Lizard Killer",ja="リザードキラー",element=6,icon_id=46,range=0,targets=0},
    [36] = {id=36,en="Bird Killer",ja="バードキラー",element=6,icon_id=46,range=0,targets=0},
    [37] = {id=37,en="Amorph Killer",ja="アモルフキラー",element=6,icon_id=46,range=0,targets=0},
    [38] = {id=38,en="Aquan Killer",ja="アクアンキラー",element=6,icon_id=46,range=0,targets=0},
    [39] = {id=39,en="Undead Killer",ja="アンデッドキラー",element=6,icon_id=46,range=0,targets=0},
    [41] = {id=41,en="Arcana Killer",ja="アルカナキラー",element=7,icon_id=47,range=0,targets=0},
    [42] = {id=42,en="Demon Killer",ja="デーモンキラー",element=6,icon_id=46,range=0,targets=0},
    [43] = {id=43,en="Dragon Killer",ja="ドラゴンキラー",element=7,icon_id=47,range=0,targets=0},
    [48] = {id=48,en="Resist Sleep",ja="レジストスリープ",element=6,icon_id=46,range=0,targets=0},
    [49] = {id=49,en="Resist Poison",ja="レジストポイズン",element=4,icon_id=44,range=0,targets=0},
    [50] = {id=50,en="Resist Paralyze",ja="レジストパライズ",element=0,icon_id=40,range=0,targets=0},
    [51] = {id=51,en="Resist Blind",ja="レジストブライン",element=6,icon_id=46,range=0,targets=0},
    [52] = {id=52,en="Resist Silence",ja="レジストサイレス",element=1,icon_id=41,range=0,targets=0},
    [53] = {id=53,en="Resist Petrify",ja="レジストペトリ",element=2,icon_id=42,range=0,targets=0},
    [54] = {id=54,en="Resist Virus",ja="レジストウィルス",element=5,icon_id=45,range=0,targets=0},
    [55] = {id=55,en="Resist Curse",ja="レジストカーズ",element=6,icon_id=46,range=0,targets=0},
    [56] = {id=56,en="Resist Stun",ja="レジストスタン",element=0,icon_id=40,range=0,targets=0},
    [57] = {id=57,en="Resist Bind",ja="レジストバインド",element=0,icon_id=40,range=0,targets=0},
    [58] = {id=58,en="Resist Gravity",ja="レジストグラビティ",element=1,icon_id=41,range=0,targets=0},
    [59] = {id=59,en="Resist Slow",ja="レジストスロウ",element=2,icon_id=42,range=0,targets=0},
    [60] = {id=60,en="Resist Charm",ja="レジストチャーム",element=6,icon_id=46,range=0,targets=0},
    [63] = {id=63,en="Resist Amnesia",ja="レジストアムネジア",element=5,icon_id=45,range=0,targets=0},
    [64] = {id=64,en="Treasure Hunter II",ja="トレジャーハンターII",element=6,icon_id=46,range=0,targets=0},
    [65] = {id=65,en="Treas. Hunter III",ja="トレジャーハンターIII",element=6,icon_id=46,range=0,targets=0},
    [66] = {id=66,en="Kick Attacks",ja="蹴撃",element=6,icon_id=46,range=0,targets=0},
    [67] = {id=67,en="Subtle Blow",ja="モクシャ",element=2,icon_id=42,range=0,targets=0},
    [68] = {id=68,en="Assassin",ja="アサシン",element=2,icon_id=42,range=0,targets=0},
    [69] = {id=69,en="Divine Veil",ja="女神の慈悲",element=6,icon_id=46,range=0,targets=0},
    [70] = {id=70,en="Zanshin",ja="残心",element=6,icon_id=46,range=0,targets=0},
    [71] = {id=71,en="Savagery",ja="サベッジリ",element=6,icon_id=46,range=0,targets=0},
    [72] = {id=72,en="Aggressive Aim",ja="アグレシブエイム",element=6,icon_id=46,range=0,targets=0},
    [73] = {id=73,en="Invigorate",ja="練気",element=6,icon_id=46,range=0,targets=0},
    [74] = {id=74,en="Penance",ja="発剄",element=6,icon_id=46,range=0,targets=0},
    [75] = {id=75,en="Aura Steal",ja="オーラスティール",element=6,icon_id=46,range=0,targets=0},
    [76] = {id=76,en="Ambush",ja="アンブッシュ",element=6,icon_id=46,range=0,targets=0},
    [77] = {id=77,en="Iron Will",ja="アイアンウィル",element=6,icon_id=46,range=0,targets=0},
    [78] = {id=78,en="Guardian",ja="ガーディアン",element=6,icon_id=46,range=0,targets=0},
    [79] = {id=79,en="Muted Soul",ja="ミューテッドソウル",element=6,icon_id=46,range=0,targets=0},
    [80] = {id=80,en="Desperate Blows",ja="デスペレートブロー",element=6,icon_id=46,range=0,targets=0},
    [81] = {id=81,en="Beast Affinity",ja="ビーストアフニティ",element=6,icon_id=46,range=0,targets=0},
    [82] = {id=82,en="Beast Healer",ja="ビーストヒーラー",element=6,icon_id=46,range=0,targets=0},
    [83] = {id=83,en="Snapshot",ja="スナップショット",element=6,icon_id=46,range=0,targets=0},
    [84] = {id=84,en="Recycle",ja="リサイクル",element=6,icon_id=46,range=0,targets=0},
    [85] = {id=85,en="Ikishoten",ja="意気衝天",element=6,icon_id=46,range=0,targets=0},
    [86] = {id=86,en="Overwhelm",ja="正正堂堂",element=6,icon_id=46,range=0,targets=0},
    [87] = {id=87,en="Ninja Tool Expert.",ja="忍具の知識",element=6,icon_id=46,range=0,targets=0},
    [88] = {id=88,en="Empathy",ja="エンパシー",element=6,icon_id=46,range=0,targets=0},
    [89] = {id=89,en="Strafe",ja="ストレイフ",element=6,icon_id=46,range=0,targets=0},
    [90] = {id=90,en="Enchainment",ja="エンチェーンメント",element=6,icon_id=46,range=0,targets=0},
    [91] = {id=91,en="Assimilation",ja="アシミレーション",element=6,icon_id=46,range=0,targets=0},
    [92] = {id=92,en="Winning Streak",ja="ウィニングストリーク",element=6,icon_id=46,range=0,targets=0},
    [93] = {id=93,en="Loaded Deck",ja="ローデッドデッキ",element=6,icon_id=46,range=0,targets=0},
    [94] = {id=94,en="Fine-Tuning",ja="微調整",element=6,icon_id=46,range=0,targets=0},
    [95] = {id=95,en="Optimization",ja="最適化",element=6,icon_id=46,range=0,targets=0},
    [96] = {id=96,en="Closed Position",ja="Ｃ・ポジション",element=6,icon_id=46,range=0,targets=0},
    [97] = {id=97,en="Stormsurge",ja="陣頭指揮",element=6,icon_id=46,range=0,targets=0},
    [98] = {id=98,en="Crit. Atk. Bonus",ja="C.インクリース",element=6,icon_id=46,range=0,targets=0},
    [99] = {id=99,en="Crit. Def. Bonus",ja="C.リデュース",element=6,icon_id=46,range=0,targets=0},
    [100] = {id=100,en="Tactical Parry",ja="タクティカルパリー",element=6,icon_id=46,range=0,targets=0},
    [101] = {id=101,en="Tactical Guard",ja="タクティカルガード",element=6,icon_id=46,range=0,targets=0},
    [102] = {id=102,en="Shield Def. Bonus",ja="エクストリームガード",element=6,icon_id=46,range=0,targets=0},
    [103] = {id=103,en="Stout Servant",ja="スタウトサーヴァント",element=6,icon_id=46,range=0,targets=0},
    [104] = {id=104,en="True Shot",ja="トゥルーショット",element=6,icon_id=46,range=0,targets=0},
    [105] = {id=105,en="Blood Boon",ja="ブラッドブーン",element=6,icon_id=46,range=0,targets=0},
    [106] = {id=106,en="Skillchain Bonus",ja="連携ボーナス",element=6,icon_id=46,range=0,targets=0},
    [107] = {id=107,en="Fencer",ja="フェンサー",element=6,icon_id=46,range=0,targets=0},
    [108] = {id=108,en="Conserve TP",ja="コンサーブTP",element=6,icon_id=46,range=0,targets=0},
    [109] = {id=109,en="Occult Acumen",ja="マジックアキュメン",element=6,icon_id=46,range=0,targets=0},
    [110] = {id=110,en="Mag. Burst Bonus",ja="MB.ボーナス",element=6,icon_id=46,range=0,targets=0},
    [111] = {id=111,en="Divine Benison",ja="ディバインベニゾン",element=6,icon_id=46,range=0,targets=0},
    [112] = {id=112,en="Elemental Celerity",ja="エレメントセレリティ",element=7,icon_id=47,range=0,targets=0},
    [113] = {id=113,en="Dead Aim",ja="デッドエイム",element=6,icon_id=46,range=0,targets=0},
    [114] = {id=114,en="Tranquil Heart",ja="トランキルハート",element=6,icon_id=46,range=0,targets=0},
    [115] = {id=115,en="Stalwart Soul",ja="ストルワートソウル",element=7,icon_id=47,range=0,targets=0},
    [116] = {id=116,en="Cardinal Chant",ja="カーディナルチャント",element=6,icon_id=46,range=0,targets=0},
    [117] = {id=117,en="Tenacity",ja="テナシティ",element=6,icon_id=46,range=0,targets=0},
    [118] = {id=118,en="Inquartata",ja="インクァルタタ",element=6,icon_id=46,range=0,targets=0},
    [119] = {id=119,en="C. Recantation",ja="キュアリカント",element=6,icon_id=46,range=0,targets=0},
    [120] = {id=120,en="Primeval Zeal",ja="プライムジール",element=7,icon_id=47,range=0,targets=0},
    [121] = {id=121,en="Inspiration",ja="インスパイア",element=6,icon_id=46,range=0,targets=0},
    [122] = {id=122,en="Sleight of Sword",ja="スライトソード",element=2,icon_id=42,range=0,targets=0},
    [123] = {id=123,en="Daken",ja="打剣",element=6,icon_id=46,range=0,targets=0},
    [124] = {id=124,en="Superior",ja="スペリア",element=6,icon_id=46,range=0,targets=0},
    [125] = {id=125,en="Magic Acc. Bonus",ja="魔法命中率アップ",element=6,icon_id=46,range=0,targets=0},
    [126] = {id=126,en="Magic Eva. Bonus",ja="魔法回避率アップ",element=7,icon_id=47,range=0,targets=0},
    [127] = {id=127,en="Smite",ja="スマイト",element=0,icon_id=40,range=0,targets=0},
    [129] = {id=129,en="Damage Limit+",ja="ダメージ上限アップ",element=0,icon_id=40,range=0,targets=0},
    [130] = {id=130,en="Animus Solace",ja="ソウルオブソラス",element=6,icon_id=46,range=0,targets=0},
    [131] = {id=131,en="Animus Misery",ja="ソウルオブミゼリ",element=6,icon_id=46,range=0,targets=0},
    [132] = {id=132,en="Con Anima",ja="コンアニマ",element=6,icon_id=46,range=0,targets=0},
    [133] = {id=133,en="Con Brio",ja="コンブリオ",element=6,icon_id=46,range=0,targets=0},
    [134] = {id=134,en="WS Damage Boost",ja="WSダメージアップ",element=6,icon_id=46,range=0,targets=0},
    [135] = {id=135,en="Max. HP Boost  II",ja="HPmaxアップII",element=6,icon_id=46,range=0,targets=0},
}, {"id", "en", "ja", "element", "icon_id", "range", "targets"}

--[[
Copyright © 2013-2019, Windower
All rights reserved.

Redistribution and use in source and binary forms, with or without modification, are permitted provided that the following conditions are met:

    * Redistributions of source code must retain the above copyright notice, this list of conditions and the following disclaimer.
    * Redistributions in binary form must reproduce the above copyright notice, this list of conditions and the following disclaimer in the documentation and/or other materials provided with the distribution.
    * Neither the name of Windower nor the names of its contributors may be used to endorse or promote products derived from this software without specific prior written permission.

THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL Windower BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
]]
