-- Automatically generated file: Merit Points

return {
    [64] = {id=64,en="Max HP",ja="HP上限",endesc="Adjust your maximum HP by 10 points.",jadesc="能力値1でHP上限を10ポイントアップします。"},
    [66] = {id=66,en="Max MP",ja="MP上限",endesc="Adjust your maximum MP by 10 points.",jadesc="能力値1でMP上限を10ポイントアップします。"},
    [68] = {id=68,en="Maximum Merit Points",ja="メリットポイント上限",endesc="Adjust your maximum number of merit points by 1 point.",jadesc="能力値1でメリットポイント上限を1ポイントアップ\nします。"},
    [128] = {id=128,en="STR",ja="STR",endesc="Adjust your STR by 1 point.",jadesc="能力値1でSTRを1ポイントアップします。"},
    [130] = {id=130,en="DEX",ja="DEX",endesc="Adjust your DEX by 1 point.",jadesc="能力値1でDEXを1ポイントアップします。"},
    [132] = {id=132,en="VIT",ja="VIT",endesc="Adjust your VIT by 1 point.",jadesc="能力値1でVITを1ポイントアップします。"},
    [134] = {id=134,en="AGI",ja="AGI",endesc="Adjust your AGI by 1 point.",jadesc="能力値1でAGIを1ポイントアップします。"},
    [136] = {id=136,en="INT",ja="INT",endesc="Adjust your INT by 1 point.",jadesc="能力値1でINTを1ポイントアップします。"},
    [138] = {id=138,en="MND",ja="MND",endesc="Adjust your MND by 1 point.",jadesc="能力値1でMNDを1ポイントアップします。"},
    [140] = {id=140,en="CHR",ja="CHR",endesc="Adjust your CHR by 1 point.",jadesc="能力値1でCHRを1ポイントアップします。"},
    [192] = {id=192,en="Hand-to-Hand Skill",ja="格闘スキル",endesc="Adjust your hand-to-hand skill by 2 points.",jadesc="能力値1で格闘スキルを2ポイントアップします。"},
    [194] = {id=194,en="Dagger Skill",ja="短剣スキル",endesc="Adjust your dagger skill by 2 points.",jadesc="能力値1で短剣スキルを2ポイントアップします。"},
    [196] = {id=196,en="Sword Skill",ja="片手剣スキル",endesc="Adjust your sword skill by 2 points.",jadesc="能力値1で片手剣スキルを2ポイントアップします。"},
    [198] = {id=198,en="Great Sword Skill",ja="両手剣スキル",endesc="Adjust your great sword skill by 2 points.",jadesc="能力値1で両手剣スキルを2ポイントアップします。"},
    [200] = {id=200,en="Axe Skill",ja="片手斧スキル",endesc="Adjust your axe skill by 2 points.",jadesc="能力値1で片手斧スキルを2ポイントアップします。"},
    [202] = {id=202,en="Great Axe Skill",ja="両手斧スキル",endesc="Adjust your great axe skill by 2 points.",jadesc="能力値1で両手斧スキルを2ポイントアップします。"},
    [204] = {id=204,en="Scythe Skill",ja="両手鎌スキル",endesc="Adjust your scythe skill by 2 points.",jadesc="能力値1で両手鎌スキルを2ポイントアップします。"},
    [206] = {id=206,en="Polearm Skill",ja="両手槍スキル",endesc="Adjust your polearm skill by 2 points.",jadesc="能力値1で両手槍スキルを2ポイントアップします。"},
    [208] = {id=208,en="Katana Skill",ja="片手刀スキル",endesc="Adjust your katana skill by 2 points.",jadesc="能力値1で片手刀スキルを2ポイントアップします。"},
    [210] = {id=210,en="Great Katana Skill",ja="両手刀スキル",endesc="Adjust your great katana skill by 2 points.",jadesc="能力値1で両手刀スキルを2ポイントアップします。"},
    [212] = {id=212,en="Club Skill",ja="片手棍スキル",endesc="Adjust your club skill by 2 points.",jadesc="能力値1で片手棍スキルを2ポイントアップします。"},
    [214] = {id=214,en="Staff Skill",ja="両手棍スキル",endesc="Adjust your staff skill by 2 points.",jadesc="能力値1で両手棍スキルを2ポイントアップします。"},
    [216] = {id=216,en="Archery Skill",ja="弓術スキル",endesc="Adjust your archery skill by 2 points.",jadesc="能力値1で弓術スキルを2ポイントアップします。"},
    [218] = {id=218,en="Marksmanship Skill",ja="射撃スキル",endesc="Adjust your marksmanship skill by 2 points.",jadesc="能力値1で射撃スキルを2ポイントアップします。"},
    [220] = {id=220,en="Throwing Skill",ja="投てきスキル",endesc="Adjust your throwing skill by 2 points.",jadesc="能力値1で投てきスキルを2ポイントアップします。"},
    [222] = {id=222,en="Guarding Skill",ja="ガードスキル",endesc="Adjust your guarding skill by 2 points.",jadesc="能力値1でガードスキルを2ポイントアップします。"},
    [224] = {id=224,en="Evasion Skill",ja="回避スキル",endesc="Adjust your evasion skill by 2 points.",jadesc="能力値1で回避スキルを2ポイントアップします。"},
    [226] = {id=226,en="Shield Skill",ja="盾スキル",endesc="Adjust your shield skill by 2 points.",jadesc="能力値1で盾スキルを2ポイントアップします。"},
    [228] = {id=228,en="Parrying Skill",ja="受け流しスキル",endesc="Adjust your parrying skill by 2 points.",jadesc="能力値1で受け流しスキルを2ポイントアップします。"},
    [256] = {id=256,en="Divine Magic Skill",ja="神聖魔法スキル",endesc="Adjust your divine magic skill by 2 points.",jadesc="能力値1で神聖魔法スキルを2ポイントアップします。"},
    [258] = {id=258,en="Healing Magic Skill",ja="回復魔法スキル",endesc="Adjust your healing magic skill by 2 points.",jadesc="能力値1で回復魔法スキルを2ポイントアップします。"},
    [260] = {id=260,en="Enhancing Magic Skill",ja="強化魔法スキル",endesc="Adjust your enhancing magic skill by 2 points.",jadesc="能力値1で強化魔法スキルを2ポイントアップします。"},
    [262] = {id=262,en="Enfeebling Magic Skill",ja="弱体魔法スキル",endesc="Adjust your enfeebling magic skill by 2 points.",jadesc="能力値1で弱体魔法スキルを2ポイントアップします。"},
    [264] = {id=264,en="Elemental Magic Skill",ja="精霊魔法スキル",endesc="Adjust your elemental magic skill by 2 points.",jadesc="能力値1で精霊魔法スキルを2ポイントアップします。"},
    [266] = {id=266,en="Dark Magic Skill",ja="暗黒魔法スキル",endesc="Adjust your dark magic skill by 2 points.",jadesc="能力値1で暗黒魔法スキルを2ポイントアップします。"},
    [268] = {id=268,en="Summoning Magic Skill",ja="召喚魔法スキル",endesc="Adjust your summoning magic skill by 2 points.",jadesc="能力値1で召喚魔法スキルを2ポイントアップします。"},
    [270] = {id=270,en="Ninjutsu Skill",ja="忍術スキル",endesc="Adjust your ninjutsu skill by 2 points.",jadesc="能力値1で忍術スキルを2ポイントアップします。"},
    [272] = {id=272,en="Singing Skill",ja="歌唱スキル",endesc="Adjust your singing skill by 2 points.",jadesc="能力値1で歌唱スキルを2ポイントアップします。"},
    [274] = {id=274,en="String Instrument Skill",ja="弦楽器スキル",endesc="Adjust your string instrument skill by 2 points.",jadesc="能力値1で弦楽器スキルを2ポイントアップします。"},
    [276] = {id=276,en="Wind Instrument Skill",ja="管楽器スキル",endesc="Adjust your wind instrument skill by 2 points.",jadesc="能力値1で管楽器スキルを2ポイントアップします。"},
    [278] = {id=278,en="Blue Magic Skill",ja="青魔法スキル",endesc="Adjust your blue magic skill by 2 points.",jadesc="能力値1で青魔法スキルを2ポイントアップします。"},
    [280] = {id=280,en="Geomancy Skill",ja="風水魔法スキル",endesc="Adjust your geomancy skill by 2 points.",jadesc="能力値1で風水魔法スキルを2ポイントアップします。"},
    [282] = {id=282,en="Handbell Skill",ja="風水鈴スキル",endesc="Adjust your handbell skill by 2 points.",jadesc="能力値1で風水鈴スキルを2ポイントアップします。"},
    [320] = {id=320,en="Enmity Increase",ja="敵対心+",endesc="Increase your enmity 1 point.",jadesc="能力値1で敵対心を+1します。"},
    [322] = {id=322,en="Enmity Decrease",ja="敵対心-",endesc="Decrease your enmity 1 point.",jadesc="能力値1で敵対心を-1します。"},
    [324] = {id=324,en="Critical Hit Rate",ja="クリティカルヒット率",endesc="Adjust your critical hit rate by 1 percent.",jadesc="能力値1で敵に与えるクリティカルヒット確率を1%アップします。"},
    [326] = {id=326,en="Enemy Critical Hit Rate",ja="被クリティカルヒット率",endesc="Adjust enemies' critical hit rate by 1 percent.",jadesc="能力値1で敵からのクリティカルヒット確率を1%ダウンします。"},
    [328] = {id=328,en="Spell Interruption Rate",ja="詠唱中断率",endesc="Adjust your spell interruption rate by 2 percent.",jadesc="能力値1で詠唱中断率を2%ダウンします。"},
    [384] = {id=384,en="Berserk Recast",ja="バーサク使用間隔",endesc="Shorten recast time by 10 seconds.",jadesc="能力値1で使用間隔を10秒短縮します。"},
    [386] = {id=386,en="Defender Recast",ja="ディフェンダー使用間隔",endesc="Shorten recast time by 6 seconds.",jadesc="能力値1で使用間隔を6秒短縮します。"},
    [388] = {id=388,en="Warcry Recast",ja="ウォークライ使用間隔",endesc="Shorten recast time by 10 seconds.",jadesc="能力値1で使用間隔を10秒短縮します。"},
    [390] = {id=390,en="Aggressor Recast",ja="アグレッサー使用間隔",endesc="Shorten recast time by 10 seconds.",jadesc="能力値1で使用間隔を10秒短縮します。"},
    [392] = {id=392,en="Double Attack Rate",ja="ダブルアタック確率",endesc="Increase double attack rate by 1 percent.",jadesc="能力値1でダブルアタック確率を1%アップします。"},
    [448] = {id=448,en="Focus Recast",ja="集中使用間隔",endesc="Shorten recast time by 10 seconds.",jadesc="能力値1で使用間隔を10秒短縮します。"},
    [450] = {id=450,en="Dodge Recast",ja="回避使用間隔",endesc="Shorten recast time by 10 seconds.",jadesc="能力値1で使用間隔を10秒短縮します。"},
    [452] = {id=452,en="Chakra Recast",ja="チャクラ使用間隔",endesc="Shorten recast time by 10 seconds.",jadesc="能力値1で使用間隔を10秒短縮します。"},
    [454] = {id=454,en="Counter Rate",ja="カウンター確率",endesc="Increase counter attack rate by 1 percent.",jadesc="能力値1でカウンター確率を1%アップします。"},
    [456] = {id=456,en="Kick Attack Rate",ja="蹴撃確率",endesc="Increase kick attack rate by 1 percent.",jadesc="能力値1で蹴撃確率を1%アップします。"},
    [512] = {id=512,en="Divine Seal Recast",ja="女神の印使用間隔",endesc="Shorten recast time by 20 seconds.",jadesc="能力値1で使用間隔を20秒短縮します。"},
    [514] = {id=514,en="Cure Cast Time",ja="ケアル詠唱時間",endesc="Shorten cast time of all Cure spells by 4 percent.",jadesc="能力値1でケアルの詠唱時間を4%短縮します。"},
    [516] = {id=516,en="Bar Spell Effect",ja="属性耐性魔法効果",endesc="Increase potency of Bar spells and add a magic defense bonus of 2 points.",jadesc="能力値1で属性耐性魔法の属性耐性、および魔法防御力を+2します。"},
    [518] = {id=518,en="Banish Effect",ja="バニシュ効果",endesc="Increase damage of Banish by 2, and length of def. down effect by 2 seconds.",jadesc="能力値1でバニシュの魔法攻撃力を+2、特殊防御力ダウン時間を2秒延長します。"},
    [520] = {id=520,en="Regen Effect",ja="リジェネ効果",endesc="Increase the amount of HP recovered each interval by 1.",jadesc="リジェネの単位時間あたりの回復量が、能力値分増加します。"},
    [576] = {id=576,en="Elemental Seal Recast",ja="精霊の印使用間隔",endesc="Shorten recast time by 20 seconds.",jadesc="能力値1で使用間隔を20秒短縮します。"},
    [578] = {id=578,en="Fire Magic Potency",ja="火属性魔法攻撃力",endesc="Increase the potency of Fire spells by 2.",jadesc="能力値1で火属性魔法攻撃力を+2します。"},
    [580] = {id=580,en="Ice Magic Potency",ja="氷属性魔法攻撃力",endesc="Increase the potency of Ice spells by 2.",jadesc="能力値1で氷属性魔法攻撃力を+2します。"},
    [582] = {id=582,en="Wind Magic Potency",ja="風属性魔法攻撃力",endesc="Increase the potency of Wind spells by 2.",jadesc="能力値1で風属性魔法攻撃力を+2します。"},
    [584] = {id=584,en="Earth Magic Potency",ja="土属性魔法攻撃力",endesc="Increase the potency of Earth spells by 2.",jadesc="能力値1で土属性魔法攻撃力を+2します。"},
    [586] = {id=586,en="Lightning Magic Potency",ja="雷属性魔法攻撃力",endesc="Increase the potency of Lightning spells by 2.",jadesc="能力値1で雷属性魔法攻撃力を+2します。"},
    [588] = {id=588,en="Water Magic Potency",ja="水属性魔法攻撃力",endesc="Increase the potency of Water spells by 2.",jadesc="能力値1で水属性魔法攻撃力を+2します。"},
    [640] = {id=640,en="Convert Recast",ja="コンバート使用間隔",endesc="Shorten recast time by 20 seconds.",jadesc="能力値1で使用間隔を20秒短縮します。"},
    [642] = {id=642,en="Fire Magic Accuracy",ja="火属性魔法命中率",endesc="Increase the accuracy of Fire spells by 3.",jadesc="能力値1で火属性魔法命中率を+3します。"},
    [644] = {id=644,en="Ice Magic Accuracy",ja="氷属性魔法命中率",endesc="Increase the accuracy of Ice spells by 3.",jadesc="能力値1で氷属性魔法命中率を+3します。"},
    [646] = {id=646,en="Wind Magic Accuracy",ja="風属性魔法命中率",endesc="Increase the accuracy of Wind spells by 3.",jadesc="能力値1で風属性魔法命中率を+3します。"},
    [648] = {id=648,en="Earth Magic Accuracy",ja="土属性魔法命中率",endesc="Increase the accuracy of Earth spells by 3.",jadesc="能力値1で土属性魔法命中率を+3します。"},
    [650] = {id=650,en="Lightning Magic Accuracy",ja="雷属性魔法命中率",endesc="Increase the accuracy of Lightning spells by 3.",jadesc="能力値1で雷属性魔法命中率を+3します。"},
    [652] = {id=652,en="Water Magic Accuracy",ja="水属性魔法命中率",endesc="Increase the accuracy of Water spells by 3.",jadesc="能力値1で水属性魔法命中率を+3します。"},
    [704] = {id=704,en="Flee Recast",ja="とんずら使用間隔",endesc="Shorten recast time by 10 seconds.",jadesc="能力値1で使用間隔を10秒短縮します。"},
    [706] = {id=706,en="Hide Recast",ja="かくれる使用間隔",endesc="Shorten recast time by 10 seconds.",jadesc="能力値1で使用間隔を10秒短縮します。"},
    [708] = {id=708,en="Sneak Attack Recast",ja="不意打ち使用間隔",endesc="Shorten recast time by 2 seconds.",jadesc="能力値1で使用間隔を2秒短縮します。"},
    [710] = {id=710,en="Trick Attack Recast",ja="だまし討ち使用間隔",endesc="Shorten recast time by 2 seconds.",jadesc="能力値1で使用間隔を2秒短縮します。"},
    [712] = {id=712,en="Triple Attack Rate",ja="トリプルアタック確率",endesc="Increase triple attack rate by 1 percent.",jadesc="能力値1でトリプルアタック確率を1%アップします。"},
    [768] = {id=768,en="Shield Bash Recast",ja="シールドバッシュ使用間隔",endesc="Shorten recast time by 6 seconds.",jadesc="能力値1で使用間隔を6秒短縮します。"},
    [770] = {id=770,en="Holy Circle Recast",ja="ホーリーサークル使用間隔",endesc="Shorten recast time by 10 seconds.",jadesc="能力値1で使用間隔を10秒短縮します。"},
    [772] = {id=772,en="Sentinel Recast",ja="センチネル使用間隔",endesc="Shorten recast time by 10 seconds.",jadesc="能力値1で使用間隔を10秒短縮します。"},
    [774] = {id=774,en="Cover Effect Length",ja="かばう効果時間",endesc="Lengthen time of effect by 4 seconds.",jadesc="能力値1で効果時間を4秒延長します。"},
    [776] = {id=776,en="Rampart Recast",ja="ランパート使用間隔",endesc="Shorten recast time by 10 seconds.",jadesc="能力値1で使用間隔を10秒短縮します。"},
    [832] = {id=832,en="Souleater Recast",ja="暗黒使用間隔",endesc="Shorten recast time by 12 seconds.",jadesc="能力値1で使用間隔を12秒短縮します。"},
    [834] = {id=834,en="Arcane Circle Recast",ja="アルケインサークル使用間隔",endesc="Shorten recast time by 10 seconds.",jadesc="能力値1で使用間隔を10秒短縮します。"},
    [836] = {id=836,en="Last Resort Recast",ja="ラストリゾート使用間隔",endesc="Shorten recast time by 10 seconds.",jadesc="能力値1で使用間隔を10秒短縮します。"},
    [838] = {id=838,en="Last Resort Effect",ja="ラストリゾート効果",endesc="Increase attacks by 2 percent, but lower defense by 2 percent.",jadesc="能力値1で攻撃力を2%アップ、防御力を2%ダウンします。"},
    [840] = {id=840,en="Weapon Bash Recast",ja="ウェポンバッシュ使用間隔",endesc="Shorten recast time by 6 seconds.",jadesc="能力値1で使用間隔を6秒短縮します。"},
    [896] = {id=896,en="Killer Effects",ja="キラー確率",endesc="Increase intimidation rate on all killer effects by 1 percent.",jadesc="能力値1で所持するキラー確率を1%アップします。"},
    [898] = {id=898,en="Reward Recast",ja="いたわる使用間隔",endesc="Shorten recast time by 3 seconds.",jadesc="能力値1で使用間隔を3秒短縮します。"},
    [900] = {id=900,en="Call Beast Recast",ja="よびだす使用間隔",endesc="Shorten recast time by 10 seconds.",jadesc="能力値1で使用間隔を10秒短縮します。"},
    [902] = {id=902,en="Sic Recast",ja="ほんきだせ使用間隔",endesc="Shorten recast time for Sic by 2 seconds, and Ready by 1 second.",jadesc="能力値1でほんきだせの使用間隔を2秒、しじをさせろの使用間隔を1秒短縮します。"},
    [904] = {id=904,en="Tame Recast",ja="なだめる使用間隔",endesc="Shorten recast time by 20 seconds.",jadesc="能力値1で使用間隔を20秒短縮します。"},
    [960] = {id=960,en="Lullaby Recast",ja="ララバイ使用間隔",endesc="Shorten recast time by 1 second.",jadesc="能力値1で使用間隔を1秒短縮します。"},
    [962] = {id=962,en="Finale Recast",ja="フィナーレ使用間隔",endesc="Shorten recast time by 1 second.",jadesc="能力値1で使用間隔を1秒短縮します。"},
    [964] = {id=964,en="Minne Effect",ja="ミンネ効果",endesc="Increase defense enhancement by 2.",jadesc="能力値1で防御力を+2します。"},
    [966] = {id=966,en="Minuet Effect",ja="メヌエット効果",endesc="Increase attack enhancement by 1.",jadesc="能力値1で攻撃力を+1します。"},
    [968] = {id=968,en="Madrigal Effect",ja="マドリガル効果",endesc="Increase melee accuracy enhancement by 1.",jadesc="能力値1で近接攻撃の命中率を+1します。"},
    [1024] = {id=1024,en="Scavenge Effect",ja="スカベンジ効果",endesc="Increase the chance of finding ammunition by 5 percent.",jadesc="能力値1で矢弾回収率を5%アップします。"},
    [1026] = {id=1026,en="Camouflage Recast",ja="カモフラージュ使用間隔",endesc="Shorten recast time by 10 seconds.",jadesc="能力値1で使用間隔を10秒短縮します。"},
    [1028] = {id=1028,en="Sharpshot Recast",ja="狙い撃ち使用間隔",endesc="Shorten recast time by 10 seconds.",jadesc="能力値1で使用間隔を10秒短縮します。"},
    [1030] = {id=1030,en="Unlimited Shot Recast",ja="エンドレスショット使用間隔",endesc="Shorten recast time by 6 seconds.",jadesc="能力値1で使用間隔を6秒短縮します。"},
    [1032] = {id=1032,en="Rapid Shot Rate",ja="ラピッドショット確率",endesc="Increase rapid shot rate by 1 percent.",jadesc="能力値1でラピッドショット確率を1%アップします。"},
    [1088] = {id=1088,en="Third Eye Recast",ja="心眼使用間隔",endesc="Shorten recast time by 2 seconds.",jadesc="能力値1で使用間隔を2秒短縮します。"},
    [1090] = {id=1090,en="Warding Circle Recast",ja="護摩の守護円使用間隔",endesc="Shorten recast time by 10 seconds.",jadesc="能力値1で使用間隔を10秒短縮します。"},
    [1092] = {id=1092,en="Store TP Effect",ja="ストアTP効果",endesc="Increase amount of TP stored by 2.",jadesc="能力値1でストアTPを+2します。"},
    [1094] = {id=1094,en="Meditate Recast",ja="黙想使用間隔",endesc="Shorten recast time by 6 seconds.",jadesc="能力値1で使用間隔を6秒短縮します。"},
    [1096] = {id=1096,en="Zanshin Attack Rate",ja="残心確率",endesc="Increase Zanshin attack rate by 1 percent.",jadesc="能力値1で残心確率を1%アップします。"},
    [1152] = {id=1152,en="Subtle Blow Effect",ja="モクシャ効果",endesc="Increase subtle blow effect by 1.",jadesc="能力値1でモクシャを+1します。"},
    [1154] = {id=1154,en="Katon Effect",ja="火遁の術効果",endesc="Increase damage by 2, and length of water resistance down effect by 2 seconds.",jadesc="能力値1で火遁の術攻撃力を+2、属性防御ダウン時間を2秒延長します。"},
    [1156] = {id=1156,en="Hyoton Effect",ja="氷遁の術効果",endesc="Increase damage by 2, and length of fire resistance down effect by 2 seconds.",jadesc="能力値1で氷遁の術攻撃力を+2、属性防御ダウン時間を2秒延長します。"},
    [1158] = {id=1158,en="Huton Effect",ja="風遁の術効果",endesc="Increase damage by 2, and length of ice resistance down effect by 2 seconds.",jadesc="能力値1で風遁の術攻撃力を+2、属性防御ダウン時間を2秒延長します。"},
    [1160] = {id=1160,en="Doton Effect",ja="土遁の術効果",endesc="Increase damage by 2, and length of wind resistance down effect by 2 seconds.",jadesc="能力値1で土遁の術攻撃力を+2、属性防御ダウン時間を2秒延長します。"},
    [1162] = {id=1162,en="Raiton Effect",ja="雷遁の術効果",endesc="Increase damage by 2, and length of earth resistance down effect by 2 seconds.",jadesc="能力値1で雷遁の術攻撃力を+2、属性防御ダウン時間を2秒延長します。"},
    [1164] = {id=1164,en="Suiton Effect",ja="水遁の術効果",endesc="Increase damage by 2, and length of ltng. resistance down effect by 2 seconds.",jadesc="能力値1で水遁の術攻撃力を+2、属性防御ダウン時間を2秒延長します。"},
    [1216] = {id=1216,en="Ancient Circle Recast",ja="エンシェントサークル使用間隔",endesc="Shorten recast time by 10 seconds.",jadesc="能力値1で使用間隔を10秒短縮します。"},
    [1218] = {id=1218,en="Jump Recast",ja="ジャンプ使用間隔",endesc="Shorten recast time by 2 seconds.",jadesc="能力値1で使用間隔を2秒短縮します。"},
    [1220] = {id=1220,en="High Jump Recast",ja="ハイジャンプ使用間隔",endesc="Shorten recast time by 4 seconds.",jadesc="能力値1で使用間隔を4秒短縮します。"},
    [1222] = {id=1222,en="Super Jump Recast",ja="スーパージャンプ使用間隔",endesc="Shorten recast time by 6 seconds.",jadesc="能力値1で使用間隔を6秒短縮します。"},
    [1224] = {id=1224,en="Spirit Link Recast",ja="スピリットリンク使用間隔",endesc="Shorten recast time by 3 seconds.",jadesc="能力値1で使用間隔を3秒短縮します。"},
    [1280] = {id=1280,en="Avatar Physical Accuracy",ja="召喚獣物理命中率",endesc="Increase avatars' physical accuracy by 3.",jadesc="能力値1で召喚獣の物理命中率を+3します。"},
    [1282] = {id=1282,en="Avatar Physical Attack",ja="召喚獣物理攻撃力",endesc="Increase avatars' physical attacks by 2.",jadesc="能力値1で召喚獣の物理攻撃力を+2します。"},
    [1284] = {id=1284,en="Avatar Magical Accuracy",ja="召喚獣魔法命中率",endesc="Increase avatars' magical accuracy by 3.",jadesc="能力値1で召喚獣の魔法命中率を+3します。"},
    [1286] = {id=1286,en="Avatar Magical Attack",ja="召喚獣魔法攻撃力",endesc="Increase avatars' magical attacks by 2.",jadesc="能力値1で召喚獣の魔法攻撃力を+2します。"},
    [1288] = {id=1288,en="Summoning Magic Cast Time",ja="召喚魔法詠唱時間",endesc="Shorten cast time of all summoning magic spells by 5 percent.",jadesc="能力値1で召喚魔法の詠唱時間を5%短縮します。"},
    [1344] = {id=1344,en="Chain Affinity Recast",ja="ブルーチェーン使用間隔",endesc="Shorten recast time by 4 seconds.",jadesc="能力値1で使用間隔を4秒短縮します。"},
    [1346] = {id=1346,en="Burst Affinity Recast",ja="ブルーバースト使用間隔",endesc="Shorten recast time by 4 seconds.",jadesc="能力値1で使用間隔を4秒短縮します。"},
    [1348] = {id=1348,en="Monster Correlation",ja="モンスター相関関係効果",endesc="Increase monster family related effects by 1.",jadesc="能力値1でモンスター相関関係効果を+1します。"},
    [1350] = {id=1350,en="Physical Potency",ja="物理系青魔法攻撃力",endesc="Increase the potency of physical blue magic spells by 2.",jadesc="能力値1で物理系青魔法の攻撃力を+2します。"},
    [1352] = {id=1352,en="Magical Accuracy",ja="魔法系青魔法命中率",endesc="Increase the accuracy of magical blue magic spells by 2.",jadesc="能力値1で魔法系青魔法の命中率を+2します。"},
    [1408] = {id=1408,en="Phantom Roll Recast",ja="ファントムロール使用間隔",endesc="Shorten recast time by 2 seconds.",jadesc="能力値1で使用間隔を2秒短縮します。"},
    [1410] = {id=1410,en="Quick Draw Recast",ja="クイックドロー使用間隔",endesc="Shorten recast time by 2 seconds.",jadesc="能力値1で使用間隔を2秒短縮します。"},
    [1412] = {id=1412,en="Quick Draw Accuracy",ja="クイックドロー命中率",endesc="Increase the accuracy of Quick Draw by 2.",jadesc="能力値1でクイックドローの命中率を+2します。"},
    [1414] = {id=1414,en="Random Deal Recast",ja="ランダムディール使用間隔",endesc="Shorten recast time by 40 seconds.",jadesc="能力値1で使用間隔を40秒短縮します。"},
    [1416] = {id=1416,en="Bust Duration",ja="Bust時間短縮",endesc="Shorten the duration of the Bust penalty by 10 seconds.",jadesc="能力値1でBust時間を10秒短縮します。"},
    [1472] = {id=1472,en="Automaton Skills",ja="オートマトンスキル",endesc="Adjust valoredge, sharpshot, and stormwaker automaton skills by 2 points.",jadesc="能力値1でオートマトンの白兵戦/射撃戦/魔法戦スキルを2ポイントアップします。"},
    [1474] = {id=1474,en="Maintenance Recast",ja="フラッシング使用間隔",endesc="Shorten recast time by 3 seconds.",jadesc="能力値1で使用間隔を3秒短縮します。"},
    [1476] = {id=1476,en="Repair Effect",ja="リペアー効果",endesc="Increase amount of HP restored by 2%.",jadesc="能力値1でオートマトンのHP回復量を2%アップします"},
    [1478] = {id=1478,en="Activate Recast",ja="アクティベート使用間隔",endesc="Shorten recast time by 40 seconds.",jadesc="能力値1で使用間隔を40秒短縮します。"},
    [1480] = {id=1480,en="Repair Recast",ja="リペアー使用間隔",endesc="Shorten recast time by 3 seconds.",jadesc="能力値1で使用間隔を3秒短縮します。"},
    [1536] = {id=1536,en="Step Accuracy",ja="ステップ命中率",endesc="Increase the accuracy of Steps by 3.",jadesc="能力値1でステップの命中率を+3します。"},
    [1538] = {id=1538,en="Haste Samba Effect",ja="ヘイストサンバ効果",endesc="Increase the effect of Haste Samba by 1.",jadesc="能力値1でヘイストサンバの効果を+1します。"},
    [1540] = {id=1540,en="Reverse Flourish Effect",ja="R.フラリッシュ効果",endesc="Increase TP gained via Reverse Flourish by 30.",jadesc="能力値1でR.フラリッシュ発動時のTP変換量を+30します。"},
    [1542] = {id=1542,en="Building Flourish Effect",ja="B.フラリッシュ効果",endesc="Increase Building Flourish accuracy by 2, attack power by 1%, and critical hit rating by 1%.",jadesc="能力値1でB.フラリッシュによる命中率を+2、攻撃力を+1%、クリティカルヒット確率を+1%アップしま\nす。"},
    [1600] = {id=1600,en="Grimoire Recast",ja="グリモア使用間隔",endesc="Shorten recast time of Light Arts and Darks Arts by 2 seconds.",jadesc="能力値1で白のグリモア、黒のグリモアの使用間隔をともに2秒短縮します。"},
    [1602] = {id=1602,en="Modus Veritas Duration",ja="以逸待労の計効果時間",endesc="Increase duration of effect for Modus Veritas by 10%.",jadesc="能力値1で以逸待労の計の効果時間を10%延長しま\nす。"},
    [1604] = {id=1604,en="Helix Magic Acc./Atk.",ja="計略魔法命中率、魔法攻撃力",endesc="Increase magic accuracy by 3 and magic attack bonus by 2 for helix spells.",jadesc="能力値1で計略の魔法命中率を+3、魔法攻撃力を+2します。"},
    [1606] = {id=1606,en="Max Sublimation",ja="机上演習上限",endesc="Increase the maximum amount of MP available via Sublimation by 10.",jadesc="能力値1で机上演習によるMP蓄積量の上限を+10します。"},
    [1664] = {id=1664,en="Shijin Spiral",ja="四神円舞",endesc="Lv.96 MNK/PUP\nHand-to-Hand skill 357 or greater.\nAdjust DEX bonus by 3%.",jadesc="使用条件:Lv96～、格闘スキル357～。\nジョブ:モか。\n能力値1でDEXによるボーナスを+3%します。"},
    [1666] = {id=1666,en="Exenterator",ja="エクゼンテレター",endesc="Lv.96 WAR/RDM/THF/BST/BRD/\n RNG/NIN/COR/DNC\nDagger skill 357 or greater.\nAdjust AGI bonus by 3%.",jadesc="使用条件:Lv96～、短剣スキル357～。\nジョブ:戦赤シ獣吟狩忍コ踊。\n能力値1でAGIによるボーナスを+3%します。"},
    [1668] = {id=1668,en="Requiescat",ja="レクイエスカット",endesc="Lv.96 WAR/RDM/PLD/DRK/SAM/BLU/COR/RUN\nSword skill 357 or greater.\nAdjust MND bonus by 3%.",jadesc="使用条件:Lv96～、片手剣スキル357～。\nジョブ:戦赤ナ暗侍青コ剣。\n能力値1でMNDによるボーナスを+3%します。"},
    [1670] = {id=1670,en="Resolution",ja="レゾルーション",endesc="Lv.96 WAR/PLD/DRK/RUN\nGreat Sword skill 357 or greater.\nAdjust STR bonus by 3%.",jadesc="使用条件:Lv96～、両手剣スキル357～。\nジョブ:戦ナ暗剣。\n能力値1でSTRによるボーナスを+3%します。"},
    [1672] = {id=1672,en="Ruinator",ja="ルイネーター",endesc="Lv.96 WAR/DRK/BST/RNG/RUN\nAxe skill 357 or greater.\nAdjust STR bonus by 3%.",jadesc="使用条件:Lv96～、片手斧スキル357～。\nジョブ:戦暗獣狩剣。\n能力値1でSTRによるボーナスを+3%します。"},
    [1674] = {id=1674,en="Upheaval",ja="アップヒーバル",endesc="Lv.96 WAR/DRK/RUN\nGreat Axe skill 357 or greater.\nAdjust VIT bonus by 3%.",jadesc="使用条件:Lv96～、両手斧スキル357～。\nジョブ:戦暗剣。\n能力値1でVITによるボーナスを+3%します。"},
    [1676] = {id=1676,en="Entropy",ja="エントロピー",endesc="Lv.96 WAR/DRK/BST\nScythe skill 357 or greater.\nAdjust INT bonus by 3%.",jadesc="使用条件:Lv96～、両手鎌スキル357～。\nジョブ:戦暗獣。\n能力値1でINTによるボーナスを+3%します。"},
    [1678] = {id=1678,en="Stardiver",ja="スターダイバー",endesc="Lv.96 WAR/SAM/DRG\nPolearm skill 357 or greater.\nAdjust STR bonus by 3%.",jadesc="使用条件:Lv96～、両手槍スキル357～。\nジョブ:戦侍竜。\n能力値1でSTRによるボーナスを+3%します。"},
    [1680] = {id=1680,en="Blade: Shun",ja="瞬",endesc="Lv.96 NIN\nKatana skill 357 or greater.\nAdjust DEX bonus by 3%.",jadesc="使用条件:Lv96～、片手刀スキル357～。\nジョブ:忍。\n能力値1でDEXによるボーナスを+3%します。"},
    [1682] = {id=1682,en="Tachi: Shoha",ja="十二之太刀・照破",endesc="Lv.96 SAM\nGreat Katana skill 357 or greater.\nAdjust STR bonus by 3%.",jadesc="使用条件:Lv96～、両手刀スキル357～。\nジョブ:侍。\n能力値1でSTRによるボーナスを+3%します。"},
    [1684] = {id=1684,en="Realmrazer",ja="レルムレイザー",endesc="Lv.96 WAR/MNK/WHM/BLM/PLD/\n SMN/BLU/SCH/GEO\nClub skill 357 or greater.\nAdjust MND bonus by 3%.",jadesc="使用条件:Lv96～、片手棍スキル357～。\nジョブ:戦モ白黒ナ召青学風。\n能力値1でMNDによるボーナスを+3%します。"},
    [1686] = {id=1686,en="Shattersoul",ja="シャッターソウル",endesc="Lv.96 WAR/MNK/WHM/BLM/PLD/\n BRD/DRG/SMN/SCH/GEO\nStaff skill 357 or greater.\nAdjust INT bonus by 3%.",jadesc="使用条件:Lv96～、両手棍スキル357～。\nジョブ:戦モ白黒ナ吟竜召学風。\n能力値1でINTによるボーナスを+3%します。"},
    [1688] = {id=1688,en="Apex Arrow",ja="エイペクスアロー",endesc="Lv.96 RNG/SAM\nArchery skill 357 or greater.\nAdjust AGI bonus by 3%.",jadesc="使用条件:Lv96～、弓術スキル357～。\nジョブ:狩侍。\n能力値1でAGIによるボーナスを+3%します。"},
    [1690] = {id=1690,en="Last Stand",ja="ラストスタンド",endesc="Lv.96 THF/RNG/COR\nMarksmanship skill 357 or greater.\nAdjust AGI bonus by 3%.",jadesc="使用条件:Lv96～、射撃スキル357～。\nジョブ:シ狩コ。\n能力値1でAGIによるボーナスを+3%します。"},
    [1728] = {id=1728,en="Full Circle Effect",ja="フルサークル効果",endesc="Increase the amount of MP returned by 5 percent.",jadesc="能力値1で自身に還元されるMPを5%アップします。"},
    [1730] = {id=1730,en="Ecliptic Attrition Recast",ja="サークルエンリッチ使用間隔",endesc="Shorten recast time of Ecliptic Attrition and Lasting Emanation by 10 seconds.",jadesc="能力値1で使用間隔を10秒短縮します。\nエンデュアエマネイトの使用間隔も短縮されます。"},
    [1732] = {id=1732,en="Life Cycle Recast",ja="ライフサイクル使用間隔",endesc="Shorten recast time by 20 seconds.",jadesc="能力値1で使用間隔を20秒短縮します。"},
    [1734] = {id=1734,en="Blaze of Glory Recast",ja="グローリーブレイズ使用間隔",endesc="Shorten recast time by 20 seconds.",jadesc="能力値1で使用間隔を20秒短縮します。"},
    [1736] = {id=1736,en="Dematerialize Recast",ja="デマテリアライズ使用間隔",endesc="Shorten recast time by 20 seconds.",jadesc="能力値1で使用間隔を20秒短縮します。"},
    [1792] = {id=1792,en="Rune Enchantment Effect",ja="エンチャントルーン効果",endesc="Increase potency of runes harbored by 2 points.",jadesc="能力値1でエンチャントルーンの属性耐性を+2します"},
    [1794] = {id=1794,en="Vallation Effect",ja="ヴァレション効果",endesc="Add an elemental damage reduction to Vallation and an elemental damage reduction to Valiance of 1 point per harbored rune.",jadesc="能力値1でヴァレションの属性ダメージ軽減の効果を\nエンチャントルーン1つにつき+1します。\nヴァリエンスの属性ダメージ軽減の効果もアップします。"},
    [1796] = {id=1796,en="Lunge Effect",ja="ランジ効果",endesc="Increase the accuracy of Lunge by 3 points per harbored rune and the accuracy of Swipe by a total of 3.",jadesc="能力値1でランジの命中率をエンチャントルーン1つに\nつき+3します。\nスワイプの命中率もアップします。"},
    [1798] = {id=1798,en="Pflug Effect",ja="フルーグ効果",endesc="Enhance the likelihood of resistance activating by 1 point per harbored rune.",jadesc="能力値1でレジスト効果発動確率をエンチャントルーン\n1つにつき+1します。"},
    [1800] = {id=1800,en="Gambit Recast",ja="ガンビット使用間隔",endesc="Shorten recast time by 10 seconds.",jadesc="能力値1で使用間隔を10秒短縮します。"},
    [2048] = {id=2048,en="Warrior's Charge",ja="ウォリアーチャージ",endesc="Will double your next attack.\nRecast: 5min.\nIncrease chance of triple attack by 5 percent.",jadesc="次の一撃が2回攻撃。使用間隔:5分\n能力値1で3回攻撃になる確率を5%アップします。"},
    [2050] = {id=2050,en="Tomahawk",ja="トマホーク",endesc="Expends a throwing tomahawk to inflict a special defense down effect on an enemy. Recast: 3min.\nIncrease duration of effect by 15 seconds.",jadesc="専用の投げ斧を消費して、敵に特殊防御力ダウンの効果。使用間隔:3分\n能力値1で効果時間を15秒延長します。"},
    [2052] = {id=2052,en="Savagery",ja="サベッジリ",endesc="Adds TP bonus effect to Warcry.\nIncrease weapon skill TP bonus by 100.",jadesc="ウォークライにTPボーナスの効果を得る。\n能力値1でウェポンスキルのTPボーナスを+100\nします。"},
    [2054] = {id=2054,en="Aggressive Aim",ja="アグレシブエイム",endesc="Adds ranged accuracy bonus to Aggressor.\nIncrease ranged accuracy bonus by 4.",jadesc="アグレッサーに飛命アップの効果を得る。\n能力値1で飛命を+4します。"},
    [2112] = {id=2112,en="Mantra",ja="マントラ",endesc="Increases the max. HP of party members within area of effect. Recast: 10min. Increase effect by 4 percent.",jadesc="範囲内パーティメンバーのHPmaxをアップ。\n使用間隔:10分\n能力値1で効果を4%アップします。"},
    [2114] = {id=2114,en="Formless Strikes",ja="無想無念",endesc="While in effect, melee attacks will not be considered physical damage. No effect on weapon skills. Recast: 10min.\nIncrease effect by 5 percent.",jadesc="効果時間内、近接攻撃の攻撃属性を無属性にする。\nウェポンスキルには効果無し。使用間隔:10分\n能力値1で効果を5%アップします。"},
    [2116] = {id=2116,en="Invigorate",ja="練気",endesc="Adds a Regen effect when using Chakra. Increase duration of effect by 24 seconds.",jadesc="チャクラ発動後、一定時間リジェネ効果を得る。\n能力値1で効果時間を24秒延長します。"},
    [2118] = {id=2118,en="Penance",ja="発剄",endesc="Adds an effect to Chi Blast that inhibits an enemy's TP accumulation.\nIncrease duration of effect by 20 seconds.",jadesc="気孔弾にストアTP-の効果を得る。\n能力値1で効果時間を20秒延長します。"},
    [2176] = {id=2176,en="Martyr",ja="マーター",endesc="Sacrifices HP to heal a party member double the amount. Recast: 10min.\nIncrease amount of HP healed by 5 percent.",jadesc="標的のパーティメンバーに自身のHPの一部を倍増し\nて分け与える。使用間隔:10分\n能力値1でHP回復量を5%アップします。"},
    [2178] = {id=2178,en="Devotion",ja="デヴォーション",endesc="Sacrifices HP to grant a party member the same amount in MP. Recast: 10min.\nIncrease amount of MP granted by 5 percent.",jadesc="標的のパーティメンバーに自身のHPの一部をMPと\nして分け与える。使用間隔:10分\n能力値1でMP回復量を5%アップします。"},
    [2180] = {id=2180,en="Protectra V",ja="プロテアV",endesc="Increases the defense of party members within area of effect.\nIncrease bonus defense by 5.",jadesc="範囲内にいるパーティメンバーの防御力をアップす\nる。\n能力値1で防御力を+5します。"},
    [2182] = {id=2182,en="Shellra V",ja="シェルラV",endesc="Increases the magic defense of party members within area of effect.\nIncrease bonus magic defense by 1.",jadesc="範囲内にいるパーティメンバーの魔法防御力をアップする。\n能力値1で魔法防御力を+1します。"},
    [2240] = {id=2240,en="Flare II",ja="フレアII",endesc="Deals fire damage to an enemy and lowers its resistance against water.\nIncrease Flare II magic burst damage by 3, and magic accuracy by 5.",jadesc="敵に火属性のダメージを与え、水属性に対する防御力をダウン。\n能力値1でフレアIIのマジックバーストダメージボーナスを+3、魔法命中率を+5します。"},
    [2242] = {id=2242,en="Freeze II",ja="フリーズII",endesc="Deals ice damage to an enemy and lowers its resistance against fire.\nIncrease Freeze II magic burst damage by 3, and magic accuracy by 5.",jadesc="敵に氷属性のダメージを与え、火属性に対する防御力をダウン。\n能力値1でフリーズIIのマジックバーストダメージボーナスを+3、魔法命中率を+5します。"},
    [2244] = {id=2244,en="Tornado II",ja="トルネドII",endesc="Deals wind damage to an enemy and lowers its resistance against ice.\nIncrease Tornado II magic burst damage by 3, and magic accuracy by 5.",jadesc="敵に風属性のダメージを与え、氷属性に対する防御力をダウン。\n能力値1でトルネドIIのマジックバーストダメージボーナスを+3、魔法命中率を+5します。"},
    [2246] = {id=2246,en="Quake II",ja="クエイクII",endesc="Deals earth damage to an enemy and lowers its resistance against wind.\nIncrease Quake II magic burst damage by 3, and magic accuracy by 5.",jadesc="敵に土属性のダメージを与え、風属性に対する防御力をダウン。\n能力値1でクエイクIIのマジックバーストダメージボーナスを+3、魔法命中率を+5します。"},
    [2248] = {id=2248,en="Burst II",ja="バーストII",endesc="Deals lightning damage to an enemy and lowers its resistance against earth.\nIncrease Burst II magic burst damage by 3, and magic accuracy by 5.",jadesc="敵に雷属性のダメージを与え、土属性に対する防御力をダウン。\n能力値1でバーストIIのマジックバーストダメージボーナスを+3、魔法命中率を+5します。"},
    [2250] = {id=2250,en="Flood II",ja="フラッドII",endesc="Deals water damage to an enemy and lowers its resistance against lightning.\nIncrease Flood II magic burst damage by 3, and magic accuracy by 5.",jadesc="敵に水属性のダメージを与え、雷属性に対する防御力をダウン。\n能力値1でフラッドIIのマジックバーストダメージボーナスを+3、魔法命中率を+5します。"},
    [2304] = {id=2304,en="Dia III",ja="ディアIII",endesc="Lowers an enemy's defense and gradually deals light elemental damage.\nIncrease duration of effect by 30 seconds.",jadesc="敵を光属性のダメージがじわじわ蝕み防御力ダウン。\n能力値1で効果時間を30秒延長します。"},
    [2306] = {id=2306,en="Slow II",ja="スロウII",endesc="Reduces an enemy's attack speed. Increase Slow II effect by 1 and magic accuracy by 2. ",jadesc="敵の攻撃間隔を長くする。\n能力値1でスロウIIのスロウ効果を+1し、魔法命中率を+2します。"},
    [2308] = {id=2308,en="Paralyze II",ja="パライズII",endesc="Paralyzes an enemy.\nIncrease Paralyze II effect by 1 and magic accuracy by 2. ",jadesc="敵を麻痺させる。\n能力値1でパライズIIの麻痺確率を+1し、魔法命中率を+2します。"},
    [2310] = {id=2310,en="Phalanx II",ja="ファランクスII",endesc="Grants a party member a certain amount of damage resistance.\nIncrease Phalanx II duration by 30 seconds and damage reduction by 3.",jadesc="標的のパーティメンバーが受けるダメージを一定量軽減する。\n能力値1でファランクスIIの効果時間を30秒延長し、ダメージカット量を+3します。"},
    [2312] = {id=2312,en="Bio III",ja="バイオIII",endesc="Deals dark damage that weakens an enemy's attacks and gradually reduces its HP.\nIncrease duration of effect by 30 seconds.",jadesc="敵を闇属性のダメージがじわじわ蝕み攻撃力ダウン。\n能力値1で効果時間を30秒延長します。"},
    [2314] = {id=2314,en="Blind II",ja="ブラインII",endesc="Blinds an enemy, lowers its accuracy. Increase Blind II accuracy down effect by 1 and magic accuracy by 2.",jadesc="敵を暗闇で捕らえ、命中率ダウン。\n能力値1でブラインIIの命中ダウン効果を+1し、魔法命中率を+2します。"},
    [2368] = {id=2368,en="Assassin's Charge",ja="アサシンチャージ",endesc="Will triple your next attack.\nRecast: 5min.\nIncrease chance of fourfold attack by 5 percent.",jadesc="次の一撃が3回攻撃。使用間隔:5分\n能力値1で4回攻撃になる確率を5%アップします。"},
    [2370] = {id=2370,en="Feint",ja="フェイント",endesc="Your next successful attack will greatly reduce an enemy's evasion. Recast: 2min.\nIncrease chance of increasing Treasure Hunter effect by 25 percent.",jadesc="次の一撃を当てると、敵の回避率を短時間著しく下\nげる。使用間隔:2分\n能力値1でトレジャーハンターの効果が上がる確\n率に対して25%のボーナスを得ます。"},
    [2372] = {id=2372,en="Aura Steal",ja="オーラスティール",endesc="Adds a Dispel effect to Steal. Occasionally absorbs dispelled effect. Increase absorb rate by 20 percent.",jadesc="ぬすむにディスペル効果を得る。ディスペルした効果を吸収することがある。\n能力値1で吸収確率を20%アップします。"},
    [2374] = {id=2374,en="Ambush",ja="アンブッシュ",endesc="Grants an accuracy bonus to melee and ranged attacks from behind an enemy.\nIncrease accuracy bonus by 3.",jadesc="敵の背後からの攻撃に対して命中、飛命にボーナスを得る。\n能力値1で命中、飛命を+3します。"},
    [2432] = {id=2432,en="Fealty",ja="フィールティ",endesc="Grants a powerful resistance to enfeebling magic. Recast: 10min.\nIncrease duration by 5 seconds.",jadesc="効果時間内、弱体魔法に対して強力な耐性を得る。\n使用間隔:10分\n能力値1で効果時間を5秒延長します。"},
    [2434] = {id=2434,en="Chivalry",ja="シバルリー",endesc="Converts TP to MP. Recast: 10min.\nIncrease amount of MP granted by 5 percent.",jadesc="TPをMPに変換する。使用間隔:10分\n能力値1でMP回復量を5%アップします。"},
    [2436] = {id=2436,en="Iron Will",ja="アイアンウィル",endesc="Adds a spell interruption down effect to Rampart.\nIncrease effect by 19 percent.",jadesc="ランパートに詠唱中断率ダウンの効果を得る。\n能力値1で詠唱中断率を19%ダウンします。"},
    [2438] = {id=2438,en="Guardian",ja="ガーディアン",endesc="Reduces enmity loss while using Sentinel. Increase effect by 19 percent.",jadesc="センチネル中、敵対心が下がりにくくなる。\n能力値1で下がる敵対心を19%緩和します。"},
    [2496] = {id=2496,en="Dark Seal",ja="ダークシール",endesc="Enhances the accuracy of your next dark magic spell. Recast: 5min.\nShorten cast time of all dark magic spells by 10 percent.",jadesc="次に唱える暗黒魔法の命中率がアップ。\n使用間隔:5分\n能力値1で暗黒魔法の詠唱時間を10%短縮します。"},
    [2498] = {id=2498,en="Diabolic Eye",ja="ディアボリクアイ",endesc="Reduces max. HP, increases accuracy. Recast: 5min.\nIncrease physical attack accuracy by 5 percent.",jadesc="HPmaxダウン、命中率アップ。使用間隔:5分\n能力値1で物理命中を+5します。"},
    [2500] = {id=2500,en="Muted Soul",ja="ミューテッドソウル",endesc="Reduces enmity while using Souleater. Reduce enmity by 10.",jadesc="暗黒中の敵対心がダウン。\n能力値1で敵対心を-10します。"},
    [2502] = {id=2502,en="Desperate Blows Effect",ja="デスペレートブロー効果",endesc="Reduces delay for two-handed weapons when using Last Resort.\nReduce delay by 2 percent.",jadesc="ラストリゾートに両手武器の攻撃間隔短縮効果を得\nる。\n能力値1で両手武器に対して攻撃間隔-2%。"},
    [2560] = {id=2560,en="Feral Howl",ja="フェラルハウル",endesc="Terrorizes the target. Recast: 5min. Increase accuracy by 5 percent.",jadesc="対象を恐怖におののかせる。使用間隔:5分\n能力値1で命中率を5%アップします。"},
    [2562] = {id=2562,en="Killer Instinct",ja="K.インスティンクト",endesc="Grants your pet's Killer effect to party members within area of effect.\nParty members will also deal increased damage and take less when fighting enemies of the corresponding monster family.\nRecast: 5min.\nIncrease duration by 10 seconds.",jadesc="範囲内にいるパーティメンバーはペットの持つキラー\n能力を得て、キラー能力を得た種族に対してダメージ\nアップ、被ダメージ軽減の効果を得る。使用間隔:5分\n能力値1で効果時間を10秒延長します。"},
    [2564] = {id=2564,en="Beast Affinity",ja="ビーストアフニティ",endesc="Increases the level of pets summoned with Call Beast.\nIncrease pet level by 2.",jadesc="よびだしによるペットのレベル上限アップ。\n能力値1でレベル上限を+2します。"},
    [2566] = {id=2566,en="Beast Healer",ja="ビーストヒーラー",endesc="Enhances the Regen effect of Reward. Increase Regen amount by 1.",jadesc="いたわるによるリジェネ効果をアップ。\n能力値1でリジェネ量を+1します。"},
    [2624] = {id=2624,en="Nightingale",ja="ナイチンゲール",endesc="Halves the casting and recast times of songs. Recast: 10min.\nIncrease chance of spectacular \"Fast Cast\" effect by 25 percent.",jadesc="効果時間内、歌の詠唱時間、再詠唱時間を半減。\n使用間隔:10分\n能力値1で歌の詠唱時間が著しく速くなる確率を\n25%アップします。"},
    [2626] = {id=2626,en="Troubadour",ja="トルバドゥール",endesc="Increases the casting time for songs by 1.5 and doubles the effect duration.\nRecast: 10min.\nIncrease chance of unerring song accuracy by 25 percent.",jadesc="効果時間内、歌の詠唱時間を1.5倍、効果時間を2\n倍。使用間隔:10分\n能力値1で歌の命中率が著しく高くなる確率を25%\nアップします。"},
    [2628] = {id=2628,en="Foe Sirvente",ja="魔物のシルベント",endesc="Reduces enmity loss for party members within area of effect.\nIncrease effect by 5 percent.",jadesc="範囲内のパーティメンバーの敵対心を下がりにくくす\nる。\n能力値1で下がる敵対心を5%緩和します。"},
    [2630] = {id=2630,en="Adventurer's Dirge",ja="冒険者のダージュ",endesc="Reduces enmity for party members within area of effect.\nReduce enmity by 3.",jadesc="範囲内のパーティメンバーの敵対心をダウン。\n能力値1で敵対心を-3します。"},
    [2688] = {id=2688,en="Stealth Shot",ja="ステルスショット",endesc="Your next ranged attack will generate less enmity. Recast: 5min.\nReduce enmity by 10.",jadesc="次の遠隔攻撃による敵対心がダウン。使用間隔:5分\n能力値1で敵対心を-10します。"},
    [2690] = {id=2690,en="Flashy Shot",ja="フラッシーショット",endesc="Your next ranged attack will generate more enmity and both have increased accuracy and deal increased damage based on the level difference between you and the target. Recast: 10min.\nIncrease ranged attack by 5 percent.",jadesc="次の遠隔攻撃が敵対心アップ、標的のレベル差に\n応じて飛命とD値にボーナス。\n使用間隔:10分\n能力値1で飛攻を5%アップします。"},
    [2692] = {id=2692,en="Snapshot",ja="スナップショット",endesc="Reduces delay for ranged attacks.\nReduce delay by 2 percent.",jadesc="遠隔攻撃による攻撃間隔短縮。\n能力値1で遠隔攻撃に対して攻撃間隔-2%。"},
    [2694] = {id=2694,en="Recycle Rate",ja="リサイクル確率",endesc="Occasionally allows ranged attacks without consuming ammunition.\nIncrease rate of activation by 5 percent.",jadesc="矢弾を消費せずに遠隔攻撃ができることがある。\n能力値1で発動確率を5%アップします。"},
    [2752] = {id=2752,en="Shikikoyo",ja="士気昂揚",endesc="Shares TP above 1000 with a party member. Recast: 5min.\nSupplement TP shared by 12%.",jadesc="標的のパーティメンバーに自身の1000を超えた分の\nTPを分け与える。使用間隔:5分\n能力値1で分け与えるTPを12%アップします。"},
    [2754] = {id=2754,en="Blade Bash",ja="峰打ち",endesc="Delivers an attack that can stun the target and occasionally cause plague. Requires great katana. Recast: 3min. Increase plague duration by 15 seconds.",jadesc="両手刀で強打しスタンさせ、悪疫状態にすることが\nある。使用間隔:3分\n能力値1で悪疫状態を15秒延長します。"},
    [2756] = {id=2756,en="Ikishoten",ja="意気衝天",endesc="Increases amount of TP gained with a Zanshin attack.\nIncrease TP gained by 30.",jadesc="残心命中時にTPが多く貯まる。\n能力値1でTPを+30します。"},
    [2758] = {id=2758,en="Overwhelm",ja="正正堂堂",endesc="Grants a damage bonus to weapon skills performed face-to-face with an enemy.\nIncrease damage bonus by 5% for the first three points, and by 2% for the final 2 points.",jadesc="敵の正面からウェポンスキルを撃つ場合、ダメージにボーナスを得る。\n能力値1～3はダメージを5%ずつアップします。能力値4～5はダメージを2%ずつアップします。"},
    [2816] = {id=2816,en="Sange",ja="散華",endesc="Daken will always activate but consume shuriken.\nRecast: 5min.\nIncrease ranged accuracy by 25.",jadesc="必ず打剣が発動するようになるが、手裏剣を消費する\n使用間隔:3分\n能力値1で飛命を+25します。"},
    [2818] = {id=2818,en="Ninja Tool Expertise",ja="忍具の知識",endesc="Occasionally allows the use of ninjutsu without consuming ninja tools.\nIncrease rate of activation by 5 percent.",jadesc="忍び道具を消費せずに忍術を唱えられることがある。\n能力値1で発動確率を5%アップします。"},
    [2820] = {id=2820,en="Katon: San",ja="火遁の術:参",endesc="Uses the ninja tool, \"uchitake.\" Deals fire damage to an enemy and lowers its resistance against water.\nIncrease Katon: San magic attack by 5 and magic accuracy by 5.",jadesc="忍び道具:打竹。敵に火属性のダメージを与え、水属性に対する防御力をダウン。\n能力値1で火遁の術:参の魔法攻撃力を+5、魔法命中率を+5します。"},
    [2822] = {id=2822,en="Hyoton: San",ja="氷遁の術:参",endesc="Uses the ninja tool, \"tsurara.\" Deals ice damage to an enemy and lowers its resistance against fire.\nIncrease Hyoton: San magic attack by 5 and magic accuracy by 5.",jadesc="忍び道具:氷柱。敵に氷属性のダメージを与え、火属性に対する防御力をダウン。\n能力値1で氷遁の術:参の魔法攻撃力を+5、魔法命中率を+5します。"},
    [2824] = {id=2824,en="Huton: San",ja="風遁の術:参",endesc="Uses the ninja tool, \"kawahori-ogi.\" Deals wind damage to an enemy and lowers its resistance against ice.\nIncrease Huton: San magic attack by 5 and magic accuracy by 5.",jadesc="忍び道具:蝙蝠扇。敵に風属性のダメージを与え、氷属性に対する防御力をダウン。\n能力値1で風遁の術:参の魔法攻撃力を+5、魔法命中率を+5します。"},
    [2826] = {id=2826,en="Doton: San",ja="土遁の術:参",endesc="Uses the ninja tool, \"makibishi.\" Deals earth damage to an enemy and lowers its resistance against wind.\nIncrease Doton: San magic attack by 5 and magic accuracy by 5.",jadesc="忍び道具:撒菱。敵に土属性のダメージを与え、風属性に対する防御力をダウン。\n能力値1で土遁の術:参の魔法攻撃力を+5、魔法命中率を+5します。"},
    [2828] = {id=2828,en="Raiton: San",ja="雷遁の術:参",endesc="Uses the ninja tool, \"hiraishin.\" Deals lightning damage to an enemy and lowers its resistance against earth.\nIncrease Raiton: San magic attack by 5 and magic accuracy by 5.",jadesc="忍び道具:避雷針。敵に雷属性のダメージを与え、土属性に対する防御力をダウン。\n能力値1で雷遁の術:参の魔法攻撃力を+5、魔法命中率を+5します。"},
    [2830] = {id=2830,en="Suiton: San",ja="水遁の術:参",endesc="Uses the ninja tool, \"mizu-deppo.\" Deals water damage to an enemy and lowers its resistance against lightning.\nIncrease Suiton: San magic attack by 5 and magic accuracy by 5.",jadesc="忍び道具:水鉄砲。敵に水属性のダメージを与え、雷属性に対する防御力をダウン。\n能力値1で水遁の術:参の魔法攻撃力を+5、魔法命中率を+5します。"},
    [2880] = {id=2880,en="Deep Breathing",ja="ディープブリージング",endesc="Enhances effect of next wyvern breath. Recast: 5min.\nEnhance effect by an additional 10%.",jadesc="次に撃つ飛竜のブレスの効果がアップ。\n使用間隔:5分\n能力値1でブレス効果を10%アップします。"},
    [2882] = {id=2882,en="Angon",ja="アンゴン",endesc="Expends an angon to lower an enemy's defense. Recast: 3min.\nIncrease defense down duration by 15 seconds.",jadesc="専用の投げ槍を消費して敵の防御力をダウン。\n使用間隔:3分\n能力値1で効果時間を15秒延長します。"},
    [2884] = {id=2884,en="Empathy",ja="エンパシー",endesc="Copies beneficial status effects to wyvern when using Spirit Link.\nIncrease number of copied effects by 1 and experience points obtained by 200.",jadesc="スピリットリンクに良いステータスを飛竜にコピー\nする効果を得て、飛竜に経験値を与えられる。\n能力値1でコピーするステータス数を+1、与えられ\nる経験値を+200します。"},
    [2886] = {id=2886,en="Strafe Effect",ja="ストレイフ効果",endesc="Increases accuracy of wyvern breath. Increase accuracy by 10.",jadesc="飛竜のブレス命中率アップ。\n能力値1でブレスの命中率を+10します。"},
    [2944] = {id=2944,en="Meteor Strike",ja="メテオストライク",endesc="Ifrit Blood Pact ability. Deals fire elemental damage.\nIncrease Meteor Strike TP bonus by 400.",jadesc="イフリートの契約の履行。敵に火属性ダメージ。\n能力値1でメテオストライクのTPボーナスを+400します。"},
    [2946] = {id=2946,en="Heavenly Strike",ja="ヘヴンリーストライク",endesc="Shiva Blood Pact ability. Deals ice elemental damage.\nIncrease Heavenly Strike TP bonus by 400.",jadesc="シヴァの契約の履行。敵に氷属性ダメージ。\n能力値1でヘヴンリーストライクのTPボーナスを+400します。"},
    [2948] = {id=2948,en="Wind Blade",ja="ウインドブレード",endesc="Garuda Blood Pact ability. Deals wind elemental damage.\nIncrease Wind Blade TP bonus by 400.",jadesc="ガルーダの契約の履行。敵に風属性ダメージ。\n能力値1でウインドブレードのTPボーナスを+400します。"},
    [2950] = {id=2950,en="Geocrush",ja="ジオクラッシュ",endesc="Titan Blood Pact ability. Deals earth elemental damage.\nIncrease Geocrush TP bonus by 400.",jadesc="タイタンの契約の履行。敵に土属性ダメージ。\n能力値1でジオクラッシュのTPボーナスを+400します。"},
    [2952] = {id=2952,en="Thunderstorm",ja="サンダーストーム",endesc="Ramuh Blood Pact ability. Deals lightning elemental damage.\nIncrease Thunderstorm TP bonus by 400.",jadesc="ラムウの契約の履行。敵に雷属性ダメージ。\n能力値1でサンダーストームのTPボーナスを+400します。"},
    [2954] = {id=2954,en="Grand Fall",ja="グランドフォール",endesc="Leviathan Blood Pact ability. Deals water elemental damage.\nIncrease Grand Fall TP bonus by 400.",jadesc="リヴァイアサンの契約の履行。敵に水属性ダメージ。\n能力値1でグランドフォールのTPボーナスを+400します。"},
    [3008] = {id=3008,en="Convergence",ja="コンバージェンス",endesc="Increases the power of your next magical blue magic spell. Limits area of effect to single target. Recast: 10min.\nIncrease magic attack by 5 and magic accuracy by 5.",jadesc="次に唱える魔法系青魔法の対象範囲が単体になって威力アップ。使用間隔:10分\n能力値1で魔法攻撃力を+5、魔法命中率を+5します。"},
    [3010] = {id=3010,en="Diffusion",ja="ディフュージョン",endesc="Grants the effect of your next support blue magic spell to party members within range. Recast: 10min.\nIncrease duration by 5%.",jadesc="次に唱える補助系青魔法の効果が範囲になる。\n使用間隔:10分\n能力値1で効果時間を5%延長します。"},
    [3012] = {id=3012,en="Enchainment",ja="エンチェーンメント",endesc="Grants a TP bonus to Chain Affinity.\nIncrease TP bonus by 100.",jadesc="ブルーチェーンにTPボーナスの効果を得る。\n能力値1でTPボーナスを+100します。"},
    [3014] = {id=3014,en="Assimilation",ja="アシミレーション",endesc="Increases maximum blue magic points.\nIncrease blue magic point maximum by 1.",jadesc="青魔法ポイントの上限をアップ。\n能力値1で青魔法ポイントの上限を+1します。"},
    [3072] = {id=3072,en="Snake Eye",ja="スネークアイ",endesc="Your next roll will automatically be a 1. Recast: 5min.\nWhen current roll is 5 or higher, increase chance of rolling an 11 by 10%.",jadesc="次に振るロールの値を1にする。使用間隔:5分\n能力値1で現在のロールの値が5以上の時、11になる\nロールの値の出る確率が10%アップします。"},
    [3074] = {id=3074,en="Fold",ja="フォールド",endesc="Erases one roll or bust effect. Targets self-cast effect with the longest remaining duration. Recast: 5min.\nIncrease chance of resetting Phantom Roll recast timer by 10%.",jadesc="自身のかけたロール、及びバストの残り効果時間の\n長い方を1つ消す。使用間隔:5分\n能力値1でファントムロールの使用間隔をリセット\nする確率が10%アップします。"},
    [3076] = {id=3076,en="Winning Streak",ja="ウィニングストリーク",endesc="Extends the duration of Phantom Roll effects.\nIncrease duration of effect by 20 seconds.",jadesc="ファントムロールの効果時間を延長。\n能力値1で効果時間を20秒延長します。"},
    [3078] = {id=3078,en="Loaded Deck",ja="ローデッドデッキ",endesc="Focuses effect of Random Deal on abilities waiting on recast.\nHas a chance to fail if only one ability is waiting on recast.\nReduce chance of failure by 10%.",jadesc="ランダムディールの対象がリキャスト発生中のアビリティに絞られる。ただし、リキャスト発生中のアビリティが1つの場合はミスの可能性がある。\n能力値1でミスの確率を10%ダウンします。"},
    [3136] = {id=3136,en="Role Reversal",ja="黒衣チェンジ",endesc="Swaps HP of master and automaton. Recast: 2min.\nSupplement HP granted by 5%.",jadesc="マスターとオートマトンのHPを入れ替える。\n使用間隔:2分\n能力値1で入れ替えたHPを5%アップします。"},
    [3138] = {id=3138,en="Ventriloquy",ja="腹話術",endesc="Swaps the enmity of master and automaton for target. Recast: 1min.\nIncrease higher enmity value and decrease lower value by 5% each.",jadesc="対象モンスターの、マスターとオートマトンへの\n敵対心を入れ替える。使用間隔:1分\n能力値1で入れ替えた敵対心で高い方が5%アップ、\n低い方が5%ダウンします。"},
    [3140] = {id=3140,en="Fine-Tuning",ja="微調整",endesc="Grants a bonus to your automaton's accuracy, ranged accuracy, evasion, and magic defense.\nIncrease accuracy by 5, ranged accuracy by 5, evasion by 5, and magic defense by 5.",jadesc="オートマトンの命中、飛命、回避、魔法防御力にボーナスを得る。\n能力値1で命中を+5、飛命を+5、回避を+5、魔法防御力を+5します。"},
    [3142] = {id=3142,en="Optimization",ja="最適化",endesc="Grants a bonus to your automaton's attack, defense, and magic attack.\nIncrease attack by 5%, defense by 5%, and magic attack by 5.",jadesc="オートマトンの攻撃力、防御力、魔法攻撃力にボーナスを得る。\n能力値1で攻撃力を+5%、防御力を+5%、魔法攻撃力を+5します。"},
    [3200] = {id=3200,en="Saber Dance",ja="剣の舞い",endesc="Increases Double Attack rate, but renders waltzes unusable. Double Attack rate gradually decreases. Recast: 3min.\nIncrease samba duration by 5%.",jadesc="効果中、ダブルアタック発動率アップ、ワルツ使用\n不可。ダブルアタック発動率は徐々に減衰する。\n使用間隔:3分\n能力値1でサンバの効果時間を5%延長します。"},
    [3202] = {id=3202,en="Fan Dance",ja="扇の舞い",endesc="Reduces physical damage taken and increases enmity, but renders sambas unusable. Physical damage reduction gradually decreases with each hit taken. Recast: 3min.\nShorten waltz recast time by 5%.",jadesc="効果中、被物理ダメージカット＆敵対心アップ、サ\nンバ使用不可。被物理ダメージカット量は相手から\nの攻撃を受ける毎に徐々に減衰する。使用間隔:3分\n能力値1でワルツの使用間隔を5%短縮します。"},
    [3204] = {id=3204,en="No Foot Rise",ja="ノーフットライズ",endesc="Instantly grants additional finishing moves. Recast: 3min.\nIncrease finishing moves granted by 1.",jadesc="フィニシングムーブを貯める。使用間隔:3分\n能力値1でフィニシングムーブを+1します。"},
    [3206] = {id=3206,en="Closed Position",ja="Ｃ・ポジション",endesc="Grants a bonus to accuracy and evasion when face-to-face with an enemy.\nIncrease accuracy and evasion bonuses\nby 3.",jadesc="敵の正面にいる場合に限り、命中と回避にボーナスを得る。\n能力値1で命中を+3、回避を+3します。"},
    [3264] = {id=3264,en="Altruism",ja="不惜身命の章",endesc="Light Arts Stratagem.\nIncreases the accuracy of your next white magic spell.\nIncrease magic accuracy by 5.",jadesc="白のグリモア戦術魔道書アビリティ。\n次に唱える白魔法の命中率がアップ。\n能力値1で魔法命中率を+5します。"},
    [3266] = {id=3266,en="Focalization",ja="一心精進の章",endesc="Dark Arts Stratagem.\nIncreases the accuracy of your next black magic spell.\nIncrease magic accuracy by 5.",jadesc="黒のグリモア戦術魔道書アビリティ。\n次に唱える黒魔法の命中率がアップ。\n能力値1で魔法命中率を+5します。"},
    [3268] = {id=3268,en="Tranquility",ja="天衣無縫の章",endesc="Light Arts Stratagem.\nYour next white magic spell will generate less enmity.\nReduce enmity by 10.",jadesc="白のグリモア戦術魔道書アビリティ。\n次に唱える白魔法の敵対心をダウン。\n能力値1で敵対心を-10します。"},
    [3270] = {id=3270,en="Equanimity",ja="無憂無風の章",endesc="Dark Arts Stratagem.\nYour next black magic spell will generate less enmity.\nReduce enmity by 10.",jadesc="黒のグリモア戦術魔道書アビリティ。\n次に唱える黒魔法の敵対心をダウン。\n能力値1で敵対心を-10します。"},
    [3272] = {id=3272,en="Enlightenment",ja="大悟徹底",endesc="Optimizes both white and black magic capabilities and allows access to both addenda for your next spell. Recast: 5min.\n+5 bonus to INT and MND.",jadesc="グリモアに関わらず次の1回だけ白魔法、黒魔法とも\nに特化し、両方の補遺の魔法を詠唱可能。\n使用間隔:5分\n能力値1でINTとMNDを+5します。"},
    [3274] = {id=3274,en="Stormsurge",ja="陣頭指揮",endesc="Storm-type spells grant a bonus to attributes associated with their element. Initial bonus value: +3.\nIncrease bonus value by 1.",jadesc="陣の効果に、天候の属性に対応するステータスアップ効果を付与する。初期値:ステータス+3\n能力値1でステータスを+1します。"},
    [3392] = {id=3392,en="Mending Halation",ja="メンドハレイション",endesc="Causes your luopan to vanish and \nrestores HP of party members within area of effect. \nRecast: 5min. Increase amount of HP restored by 5 percent.",jadesc="羅盤を消失し、範囲内のパーティメンバーのHPを回\n復する。使用間隔:5分\n能力値1でHP回復量を5%アップします。"},
    [3394] = {id=3394,en="Radial Arcana",ja="レイディアルアルカナ",endesc="Causes your luopan to vanish and \nrestores MP of party members within area of effect. \nRecast: 5min. Increase amount of MP restored by 3 percent.",jadesc="羅盤を消失し、範囲内のパーティメンバーのMPを回\n復する。使用間隔:5分\n能力値1でMP回復量を3%アップします。"},
    [3396] = {id=3396,en="Curative Recantation",ja="キュアリカント",endesc="Grants a healing effect to Full Circle. \nIncrease amount of HP healed by 5 percent.",jadesc="フルサークルにHP回復の効果を得る。\n能力値1でHP回復量を5%アップします。"},
    [3398] = {id=3398,en="Primeval Zeal",ja="プライムジール",endesc="Shortens casting times of elemental magic spells while under the effects of Collimated Fervor. \nShorten cast time by 10 percent.",jadesc="コリメイトファーバー中、精霊魔法の詠唱時間短縮の\n効果を得る。能力値1で詠唱時間を10%短縮します。"},
    [3456] = {id=3456,en="Battuta",ja="バットゥタ",endesc="Increases the likelihood of parrying and deals counter damage after parrying dependent upon harbored runes. \nRecast: 5min. Increase chance of parrying by 4 percent and increase counter damage by 4 points per rune harbored.",jadesc="受け流し確率にボーナスを得る。\nさらに、受け流し発動時エンチャントルーンに依存し\nた反撃ダメージを与える。使用間隔:5分。\n能力値1で受け流し確率を4%アップ、反撃ダメージを\nエンチャントルーン１つにつき+4アップします。"},
    [3458] = {id=3458,en="Rayke",ja="レイク",endesc="Expends runes to reduce elemental resistance of the target. \nRecast: 5min. Increase duration of effect by 3 seconds.",jadesc="ルーンを消費して、対象の属性耐性をダウンさせる。\n使用間隔:5分。\n能力値1で効果時間を3秒延長します。"},
    [3460] = {id=3460,en="Inspiration",ja="インスパイア",endesc="Grants a \"Fast Cast\" effect to Vallation and Valiance. \nIncrease cast speed by 10 percent.",jadesc="ヴァレション、ヴァリエンスに魔法詠唱時間短縮の効\n果を得る。\n能力値1で魔法詠唱時間を10%短縮します。"},
    [3462] = {id=3462,en="Sleight of Sword",ja="スライトソード",endesc="Grants a \"Subtle Blow\" effect during Swordplay. \nIncrease the maximum value of Subtle Blow by 5 points.",jadesc="ソードプレイ中、モクシャの効果を得る。\n能力値1でモクシャの効果の最大値を5アップします。"},
}, {"id", "en", "ja", "endesc", "jadesc"}

--[[
Copyright © 2013-2016, Windower
All rights reserved.

Redistribution and use in source and binary forms, with or without modification, are permitted provided that the following conditions are met:

    * Redistributions of source code must retain the above copyright notice, this list of conditions and the following disclaimer.
    * Redistributions in binary form must reproduce the above copyright notice, this list of conditions and the following disclaimer in the documentation and/or other materials provided with the distribution.
    * Neither the name of Windower nor the names of its contributors may be used to endorse or promote products derived from this software without specific prior written permission.

THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL Windower BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
]]
