return function(options)
    return {
        player = {
            title = 'Player',
            style = 'normal',
            width = options.frames.player.width,
            min_height = options.frames.player.height,
            max_height = options.frames.player.height,
            resizable = true,
            moveable = true,
            closeable = false,
            color = ui.color.rgb(0,0,0,0),
        },
        target = {
            title = 'Target',
            style = 'normal',
            width = options.frames.target.width,
            min_height = options.frames.target.height,
            max_height = options.frames.target.height,
            resizable = true,
            moveable = true,
            closeable = false,
            color = ui.color.rgb(0,0,0,0),
        },
        subtarget = {
            title = 'Subtarget',
            style = 'normal',
            width = options.frames.subtarget.width,
            min_height = options.frames.subtarget.height,
            max_height = options.frames.subtarget.height,
            resizable = true,
            moveable = true,
            closeable = false,
            color = ui.color.rgb(0,0,0,0),
        },
        focustarget = {
            title = 'Focus Target',
            style = 'normal',
            width = options.frames.focustarget.width,
            min_height = options.frames.focustarget.height,
            max_height = options.frames.focustarget.height,
            resizable = true,
            moveable = true,
            closeable = false,
            color = ui.color.rgb(0,0,0,0),
        },
    }
end