local packets = require('packets')

local currencies = {}

local handler = function(p)
    local data = currencies
-- currencies 1
    data.sandoria_conquest_points = p.conquest_points[0]
    data.bastok_conquest_points = p.conquest_points[1]
    data.windurst_conquest_points = p.conquest_points[2]
    data.beastmen_seals = p.beastmen_seals
    data.kindred_seals = p.kindred_seals
    data.kindred_crests = p.kindred_crests
    data.high_kindred_crests = p.high_kindred_crests
    data.sacred_kindred_crests = p.sacred_kindred_crests
    data.ancient_beastcoins = p.ancient_beastcoins
    data.valor_points = p.valor_points
    data.scylds = p.scylds
    data.fishing_guild_points = p.guild_points[48]
    data.woodworking_guild_points = p.guild_points[49]
    data.smithing_guild_points = p.guild_points[50]
    data.goldsmithing_guild_points = p.guild_points[51]
    data.weaving_guild_points = p.guild_points[52]
    data.leathercraft_guild_points = p.guild_points[53]
    data.bonecraft_guild_points =  p.guild_points[54]
    data.alchemy_guild_points = p.guild_points[55]
    data.cooking_guild_points = p.guild_points[56]
    data.cinders = p.cinders
    data.fire_fewell = p.fewell[0]
    data.ice_fewell = p.fewell[1]
    data.wind_fewell = p.fewell[2]
    data.earth_fewell = p.fewell[3]
    data.lightning_fewell = p.fewell[4]
    data.water_fewell = p.fewell[5]
    data.light_fewell = p.fewell[6]
    data.dark_fewell = p.fewell[7]
    data.ballista_points = p.ballista_points
    data.fellow_points = p.fellow_points
    data.sandoria_chocobucks = p.chocobucks[0]
    data.bastok_chocobucks = p.chocobucks[1]
    data.windurst_chocobuck = p.chocobuck[2]
    data.daily_tally = p.daily_tally
    data.research_marks = p.research_marks
    data.wizened_tunnel_worms = p.wizened_tunnel_worms
    data.wizened_morion_worms = p.wizened_morion_worms
    data.wizened_phantom_worms = p.wizened_phantom_worms
    data.moblin_marbles = p.moblin_marbles
    data.infamy = p.infamy
    data.prestige = p.prestige
    data.legion_points = p.legion_points
    data.sparks_of_eminence = p.sparks_of_eminence
    data.shining_stars = p.shining_stars
    data.imperial_standing = p.imperial_standing
    data.leujaoam_sanctum_assault_points = p.assault_points[1]
    data.mamool_ja_assault_points = p.assault_points[2]
    data.lebros_cavern_assault_points = p.assault_points[3]
    data.periqia_assault_points = p.assault_points[4]
    data.ilrusi_atoll_assault_points = p.assault_points[5]
    data.nyzul_tokens = p.nyzul_tokens
    data.zeni = p.zeni
    data.jettons = p.jettons
    data.therion_ichor = p.therion_ichor
    data.allied_notes = p.allied_notes
    data.aman_vouchers_stored = p.aman_vouchers_stored
    data.unity_accolades = p.unity_accolades
    data.cruor = p.cruor
    data.resistance_credits = p.resistance_credits
    data.dominion_notes = p.dominion_notes
    data.5th_echelon_battle_trophies = p.battle_trophies[1]
    data.4th_echelon_battle_trophies = p.battle_trophies[2]
    data.3rd_echelon_battle_trophies = p.battle_trophies[3]
    data.2nd_echelon_battle_trophies = p.battle_trophies[4]
    data.1st_echelon_battle_trophies = p.battle_trophies[5]
    data.cave_conservation_points = p.cave_conservation_points
    data.imperial_army_id_tags = p.imperial_army_id_tags
    data.op_credits = p.op_credits
    data.traverser_stones = p.traverser_stones
    data.voidstones = p.voidstones
    data.kupofrieds_corundums = p.kupofrieds_corundums
    data.moblin_pheromone_sacks = p.moblin_pheromone_sacks
-- currencies 2
    data.bayld = p.bayld
    data.kinetic_units = p.kinetic_units
    data.coalition_imprimaturs = p.coalition_imprimaturs
    data.obsidian_fragments = p.obsidian_fragments
    data.lebondopt_wings = p.lebondopt_wings
    data.pulchridopt_wings = p.pulchridopt_wings
    data.mweya_plasm = p.mweya_plasm
    data.ghastly_stones = p.ghastly_stones
    data.ghastly_stones_1 = p['ghastly_stones_1']
    data.ghastly_stones_2 = p['ghastly_stones_2']
    data.verdigris_stones = p.verdigris_stones
    data.verdigris_stones_1 = p['verdigris_stones_1']
    data.verdigris_stones_2 = p['verdigris_stones_2']
    data.wailing_stones = p.wailing_stones
    data.wailing_stones_1 = p['wailing_stones_1']
    data.wailing_stones_2 = p['wailing_stones_2']
    data.snowslit_stones = p.snowslit_stones
    data.snowslit_stones_1 = p['snowslit_stones_1']
    data.snowslit_stones_2 = p['snowslit_stones_2']
    data.snowtip_stones = p.snowtip_stones
    data.snowtip_stones_1 = p['snowtip_stones_1']
    data.snowtip_stones_2 = p['snowtip_stones_2']
    data.snowdim_stones = p.snowdim_stones
    data.snowdim_stones_1 = p['snowdim_stones_1']
    data.snowdim_stones_2 = p['snowdim_stones_2']
    data.snoworb_stones = p.snoworb_stones
    data.snoworb_stones_1 = p['snoworb_stones_1']
    data.snoworb_stones_2 = p['snoworb_stones_2']
    data.leafslit_stones = p.leafslit_stones
    data.leafslit_stones_1 = p['leafslit_stones_1']
    data.leafslit_stones_2 = p['leafslit_stones_2']
    data.leaftip_stones = p.leaftip_stones
    data.leaftip_stones_1 = p['leaftip_stones_1']
    data.leaftip_stones_1 = p['leaftip_stones_2']
    data.leafdim_stones = p.leafdim_stones
    data.leafdim_stones_1 = p['leafdim_stones_1']
    data.leafdim_stones_2 = p['leafdim_stones_2']
    data.leaforb_stones = p.leaforb_stones
    data.leaforb_stones_1 = p['leaforb_stones_1']
    data.leaforb_stones_2 = p['leaforb_stones_2']
    data.duskslit_stones = p.duskslit_stones
    data.duskslit_stones_1 = p['duskslit_stones_1']
    data.duskslit_stones_2 = p['duskslit_stones_2']
    data.dusktip_stones = p.dusktip_stones
    data.dusktip_stones_1 = p['dusktip_stones_1']
    data.dusktip_stones_2 = p['dusktip_stones_2']
    data.duskdim_stones = p.duskdim_stones
    data.duskdim_stones_1 = p['duskdim_stones_1']
    data.duskdim_stones_2 = p['duskdim_stones_2']
    data.duskorb_stones = p.duskorb_stones
    data.duskorb_stones_1 = p['duskorb_stones_1']
    data.duskorb_stones_2 = p['duskorb_stones_2']
    data.pellucid_stone = p.pellucid_stone
    data.fern_stone = p.fern_stone
    data.taupe_stone = p.taupe_stone
    data.escha_beads = p.escha_beads
    data.escha_silt = p.escha_silt
    data.potpourri = p.potpourri
end

packets.incoming[0x113]:register(handler)
handler(packets.incoming[0x113].last)

packets.incoming[0x118]:register(handler)
handler(packets.incoming[0x118].last)

return currencies
