-- Automatically generated file: Titles

return {
    [0] = {id=0,en="N/A",ja="なし"},
    [1] = {id=1,en="Fodderchief Flayer",ja="フォッダーチーフ　フレーヤー"},
    [2] = {id=2,en="Warchief Wrecker",ja="ウォーチーフ　レッカー"},
    [3] = {id=3,en="Dread Dragon Slayer",ja="ドレッドドラゴン　スレーヤー"},
    [4] = {id=4,en="Overlord Executioner",ja="オーバーロード　エグゼキューショナー"},
    [5] = {id=5,en="Dark Dragon Slayer",ja="ダークドラゴン　スレーヤー"},
    [6] = {id=6,en="Adamantking Killer",ja="アダマンキング　キラー"},
    [7] = {id=7,en="Black Dragon Slayer",ja="ブラックドラゴン　スレーヤー"},
    [8] = {id=8,en="Manifest Mauler",ja="マニフェスト　モーラー"},
    [9] = {id=9,en="Behemoth's Bane",ja="ベヒーモス　ベーン"},
    [10] = {id=10,en="Archmage Assassin",ja="アークメイジ　アサシン"},
    [11] = {id=11,en="Hellsbane",ja="ヘルズベーン"},
    [12] = {id=12,en="Giant Killer",ja="ジャイアントキラー"},
    [13] = {id=13,en="Lich Banisher",ja="リッチ　バニッシャー"},
    [14] = {id=14,en="Jellybane",ja="ジェリーベーン"},
    [15] = {id=15,en="Bogeydowner",ja="ゴギー　ダウナー"},
    [16] = {id=16,en="Beakbender",ja="ビークベンダー"},
    [17] = {id=17,en="Skullcrusher",ja="スカルクラッシャー"},
    [18] = {id=18,en="Morbolbane",ja="モルボル　ベーン"},
    [19] = {id=19,en="Goliath Killer",ja="ゴリアテ　キラー"},
    [20] = {id=20,en="Mary's Guide",ja="メリーズガイド"},
    [21] = {id=21,en="Simurgh Poacher",ja="シムルグ　スレーヤー"},
    [22] = {id=22,en="Roc Star",ja="ロック　スター"},
    [23] = {id=23,en="Serket Breaker",ja="セルケト　ブレーカー"},
    [24] = {id=24,en="Cassienova",ja="キャシノバ"},
    [25] = {id=25,en="The Hornsplitter",ja="ホーンスプリッター"},
    [26] = {id=26,en="Tortoise Torturer",ja="トータストーチャラー"},
    [27] = {id=27,en="Mon Cherry",ja="モン　チェリー"},
    [28] = {id=28,en="Behemoth Dethroner",ja="ベヒーモス　デスローナー"},
    [29] = {id=29,en="The Vivisector",ja="ビビセクター"},
    [30] = {id=30,en="Dragon Asher",ja="ドラゴンアッシャー"},
    [31] = {id=31,en="Expeditionary Trooper",ja="遠征軍遊撃隊員"},
    [32] = {id=32,en="Bearer of the Wisewoman's Hope",ja="賢者の希望を担いし者"},
    [33] = {id=33,en="Bearer of the Eight Prayers",ja="八つの祈りを帯びし者"},
    [34] = {id=34,en="Lightweaver",ja="光の紡ぎ手"},
    [35] = {id=35,en="Destroyer of Antiquity",ja="いにしえを屠る者"},
    [36] = {id=36,en="Sealer of the Portal of the Gods",ja="神の扉を閉ざす者"},
    [37] = {id=37,en="Burier of the Illusion",ja="幻影を葬りし者"},
    [39] = {id=39,en="Family Counselor",ja="小さな親切運動家"},
    [41] = {id=41,en="Great Grappler Scorpio!?",ja="格闘家スコーピオン！？"},
    [42] = {id=42,en="Bond Fixer",ja="絆の証人"},
    [43] = {id=43,en="Vampire Hunter D-Minus",ja="低級ヴァンパイアハンター"},
    [44] = {id=44,en="Sheep's Milk Deliverer",ja="羊乳配達人"},
    [45] = {id=45,en="Bean Cuisine Salter",ja="マメ料理人手伝い"},
    [46] = {id=46,en="Total Loser",ja="ヘッポコくん"},
    [47] = {id=47,en="Doctor Shantotto's Flavor of the Month",ja="シャントット博士のお気に入り"},
    [48] = {id=48,en="Pilgrim to Holla",ja="ホラの巡礼者"},
    [49] = {id=49,en="Pilgrim to Dem",ja="デムの巡礼者"},
    [50] = {id=50,en="Pilgrim to Mea",ja="メアの巡礼者"},
    [51] = {id=51,en="Daybreak Gambler",ja="暁の勝負師"},
    [52] = {id=52,en="The Pious One",ja="信心深き者"},
    [53] = {id=53,en="A Moss Kind Person",ja="心優しき者"},
    [54] = {id=54,en="Entrance Denied",ja="門前払い"},
    [55] = {id=55,en="Apiarist",ja="ハチミツ博士"},
    [56] = {id=56,en="Rabbiter",ja="ワイルドハンター"},
    [57] = {id=57,en="Royal Grave Keeper",ja="龍王の墓守"},
    [58] = {id=58,en="Courier Extraordinaire",ja="凄腕の運び屋"},
    [59] = {id=59,en="Ronfaurian Rescuer",ja="森の救急隊員"},
    [60] = {id=60,en="Pickpocket Pincher",ja="街の名探偵"},
    [61] = {id=61,en="Fang Finder",ja="ファング"},
    [62] = {id=62,en="Faith like a Candle",ja="炎の信者"},
    [63] = {id=63,en="The Pure One",ja="清らかなる者"},
    [64] = {id=64,en="Lost Child Officer",ja="迷子引受人"},
    [65] = {id=65,en="Silencer of the Lambs",ja="沈黙の羊飼い"},
    [66] = {id=66,en="Lost & Found Officer",ja="遺失物捜索隊員"},
    [67] = {id=67,en="Green Grocer",ja="ベジタブル特急"},
    [68] = {id=68,en="The Benevolent One",ja="慈悲深き者"},
    [69] = {id=69,en="Knight in Training",ja="見習い騎士"},
    [70] = {id=70,en="Lizard Skinner",ja="リザードキラー"},
    [71] = {id=71,en="Bug Catcher",ja="虫採り名人"},
    [72] = {id=72,en="Spelunker",ja="洞窟探検隊"},
    [73] = {id=73,en="Arms Trader",ja="取引代理人"},
    [74] = {id=74,en="Traveling Medicine Man",ja="旅の調剤士"},
    [75] = {id=75,en="Cat Skinner",ja="虎ハンター"},
    [76] = {id=76,en="Carp Diem",ja="フナ釣りマイスター"},
    [77] = {id=77,en="Advertising Executive",ja="呼び込み名人"},
    [78] = {id=78,en="Third-rate Organizer",ja="下級オーガナイザー"},
    [79] = {id=79,en="Second-rate Organizer",ja="中級オーガナイザー"},
    [80] = {id=80,en="First-rate Organizer",ja="上級オーガナイザー"},
    [81] = {id=81,en="Bastok Welcoming Committee",ja="バストゥークの案内人"},
    [82] = {id=82,en="Shell Outer",ja="甲羅からの解放者"},
    [83] = {id=83,en="Bucket Fisher",ja="バケツフィッシャー"},
    [84] = {id=84,en="Pursuer of the Past",ja="過去を垣間見る者"},
    [85] = {id=85,en="Pursuer of the Truth",ja="真実の探求者"},
    [86] = {id=86,en="Mommy's Helper",ja="ママのお手伝い"},
    [87] = {id=87,en="Hot Dog",ja="スモーキー"},
    [88] = {id=88,en="Stampeder",ja="スタンピオン"},
    [89] = {id=89,en="Qiji's Friend",ja="クィジの友人"},
    [90] = {id=90,en="Qiji's Rival",ja="クィジのライバル"},
    [91] = {id=91,en="Contest Rigger",ja="勝負の采配人"},
    [92] = {id=92,en="Ringbearer",ja="怪しい運び屋"},
    [93] = {id=93,en="Kulatz Bridge Companion",ja="クラウツ橋の友人"},
    [94] = {id=94,en="Beadeaux Surveyor",ja="ベドー調査員"},
    [95] = {id=95,en="Avenger",ja="死者を弔いし者"},
    [96] = {id=96,en="Treasure Scavenger",ja="トレジャーハンター"},
    [97] = {id=97,en="Airship Denouncer",ja="飛空艇伝道師"},
    [98] = {id=98,en="Zeruhn Sweeper",ja="ツェールンスイーパー"},
    [99] = {id=99,en="Tearjerker",ja="水辺に立つ者"},
    [100] = {id=100,en="Crab Crusher",ja="クラブクラッシャー"},
    [101] = {id=101,en="Star of Ifrit",ja="イフリートの空に向かう者"},
    [102] = {id=102,en="Sorrow Drowner",ja="ラプソディコンダクター"},
    [103] = {id=103,en="Brygid-approved",ja="ブリジッドのお墨付き"},
    [104] = {id=104,en="Drachenfall Ascetic",ja="臥竜の験者"},
    [105] = {id=105,en="\"Steaming Sheep\" Regular",ja="「蒸気の羊」亭の常連客"},
    [106] = {id=106,en="Purple Belt",ja="紫帯の有段者"},
    [107] = {id=107,en="Gustaberg Tourist",ja="グスタベルグツーリスト"},
    [108] = {id=108,en="Sand Blaster",ja="砂の開拓者"},
    [109] = {id=109,en="Black Death",ja="黒の死神"},
    [111] = {id=111,en="Fresh \"North Winds\" Recruit",ja="北風団の新米"},
    [112] = {id=112,en="New \"Best of the West\" Recruit",ja="ウェスト・オブ・ビースト"},
    [113] = {id=113,en="New \"Buuma's Boomers\" Recruit",ja="ブーマガードの新米"},
    [114] = {id=114,en="Heavens Tower Gatehouse Recruit",ja="天の塔前・魔戦士隊員"},
    [115] = {id=115,en="Cat Burglar Groupie",ja="泥棒ミスラのコブン"},
    [116] = {id=116,en="Crawler Culler",ja="クロウラーバスター"},
    [117] = {id=117,en="Savior of Knowledge",ja="知識の守り手"},
    [118] = {id=118,en="Star-ordained Warrior",ja="星巡りの戦士"},
    [119] = {id=119,en="Lower than the Lowest Tunnel Worm",ja="くさったバナナ"},
    [120] = {id=120,en="Star Onion Brigade Member",ja="スターオニオンズ団員"},
    [121] = {id=121,en="Star Onion Brigadier",ja="オニオンヒーロー"},
    [122] = {id=122,en="Quick Fixer",ja="お手軽修繕屋"},
    [123] = {id=123,en="Fake-moustached Investigator",ja="つけひげの名探偵"},
    [124] = {id=124,en="Hakkuru-Rinkuru's Benefactor",ja="ハックルリンクルの恩人"},
    [125] = {id=125,en="S.O.B. Super Hero",ja="正義の味方"},
    [126] = {id=126,en="Editor's Hatchet Man",ja="編集長の刺客"},
    [127] = {id=127,en="Doctor Shantotto's Guinea Pig",ja="シャントット博士の実験台"},
    [128] = {id=128,en="Spoilsport",ja="マナー違反者"},
    [129] = {id=129,en="Super Model",ja="ナイスモデル"},
    [130] = {id=130,en="Ghostie Buster",ja="ゴーストバスター"},
    [131] = {id=131,en="Night Sky Navigator",ja="夜空の航海士"},
    [132] = {id=132,en="Fast Food Deliverer",ja="買出し部隊員"},
    [133] = {id=133,en="Cupid's Florist",ja="花鼻キューピッド"},
    [134] = {id=134,en="Tarutaru Murder Suspect",ja="殺タルタル容疑者"},
    [135] = {id=135,en="Hexer Vexer",ja="不幸な呪い師"},
    [136] = {id=136,en="Cardian Tutor",ja="カーディアン教育者"},
    [137] = {id=137,en="Deliverer of Tearful News",ja="銀色の涙の使者"},
    [138] = {id=138,en="Fossilized Sea Farer",ja="太古の海人"},
    [139] = {id=139,en="Down Piper Pipe-upperer",ja="栄光なる薔薇の笛吹き"},
    [140] = {id=140,en="Kisser Make-upper",ja="美の開拓者"},
    [141] = {id=141,en="Timekeeper",ja="時の旅人"},
    [142] = {id=142,en="Fortune-teller in Training",ja="見習い占い師"},
    [143] = {id=143,en="Torchbearer",ja="ともし火ランナー"},
    [144] = {id=144,en="Tenshodo Member",ja="天晶堂会員"},
    [145] = {id=145,en="Chocobo Trainer",ja="チョコボ調教師"},
    [146] = {id=146,en="Bringer of Bliss",ja="しあわせ宅配人"},
    [147] = {id=147,en="Activist for Kindness",ja="慈善活動家"},
    [148] = {id=148,en="Envoy to the North",ja="北への使者"},
    [149] = {id=149,en="Exorcist in Training",ja="エクソシスト見習い"},
    [150] = {id=150,en="Professional Loafer",ja="街一番の油売り"},
    [151] = {id=151,en="Clock Tower Preservationist",ja="時計塔保存嘆願者"},
    [152] = {id=152,en="Life Saver",ja="命の恩人"},
    [153] = {id=153,en="Fool's Errand Runner",ja="下級ツカイッパー"},
    [154] = {id=154,en="Card Collector",ja="カードコレクター"},
    [155] = {id=155,en="Researcher of Classics",ja="古典研究家"},
    [156] = {id=156,en="Street Sweeper",ja="街の掃除人"},
    [157] = {id=157,en="Mercy Errand Runner",ja="上級ツカイッパー"},
    [158] = {id=158,en="Two's Company",ja="第一発見者"},
    [159] = {id=159,en="Believer of Altana",ja="アルタナ教信者"},
    [160] = {id=160,en="Trader of Mysteries",ja="迷トレーダー"},
    [161] = {id=161,en="Trader of Antiquities",ja="お宝出品人"},
    [162] = {id=162,en="Trader of Renown",ja="名トレーダー"},
    [163] = {id=163,en="Brown Belt",ja="茶帯の有段者"},
    [164] = {id=164,en="Horizon Breaker",ja="オーバー・ザ・トップ"},
    [165] = {id=165,en="Goblin's Exclusive Fashion Mannequin",ja="ゴブリン専属モデル"},
    [166] = {id=166,en="Summit Breaker",ja="山の頂に立つ者"},
    [167] = {id=167,en="Sky Breaker",ja="風来坊"},
    [168] = {id=168,en="Cloud Breaker",ja="雲入道"},
    [169] = {id=169,en="Star Breaker",ja="ヴァナ・ディールのスター"},
    [170] = {id=170,en="Greedalox",ja="ヨバクリ"},
    [171] = {id=171,en="Certified Rhinostery Venturer",ja="鼻の院認可冒険者"},
    [172] = {id=172,en="Cordon Bleu Fisher",ja="釣り名人"},
    [173] = {id=173,en="Ace Angler",ja="釣り大名人"},
    [174] = {id=174,en="Lu Shang-like Fisher King",ja="太公望"},
    [175] = {id=175,en="Matchmaker",ja="愛の仲人"},
    [176] = {id=176,en="Ecologist",ja="エコロジスト"},
    [177] = {id=177,en="Li'l Cupid",ja="愛のキューピッド"},
    [178] = {id=178,en="The Love Doctor",ja="キング・オブ・ラブ"},
    [179] = {id=179,en="Savior of Love",ja="愛の救世主"},
    [180] = {id=180,en="Honorary Citizen of Selbina",ja="セルビナ名誉市民"},
    [181] = {id=181,en="Purveyor in Training",ja="食材調達人見習い"},
    [182] = {id=182,en="One-star Purveyor",ja="食材調達人"},
    [183] = {id=183,en="Two-star Purveyor",ja="目利きの調達人"},
    [184] = {id=184,en="Three-star Purveyor",ja="調達人"},
    [185] = {id=185,en="Four-star Purveyor",ja="調達の達人"},
    [186] = {id=186,en="Five-star Purveyor",ja="孤高の調達人"},
    [187] = {id=187,en="Doctor Yoran-Oran Supporter",ja="ヨランオラン博士の味方"},
    [188] = {id=188,en="Doctor Shantotto Supporter",ja="シャントット博士の味方"},
    [189] = {id=189,en="Professor Koru-Moru Supporter",ja="コルモル博士の味方"},
    [190] = {id=190,en="Rainbow Weaver",ja="虹を織りし者"},
    [191] = {id=191,en="Shadow Walker",ja="忍びの道を往く者"},
    [192] = {id=192,en="Heir to the Holy Crest",ja="聖なる印を継ぐ者"},
    [193] = {id=193,en="Bushido Blade",ja="ブシドー・ザ・ブレード"},
    [195] = {id=195,en="Paragon of Paladin Excellence",ja="高雅なる大騎士"},
    [196] = {id=196,en="Paragon of Beastmaster Excellence",ja="熾烈なる大獣使い"},
    [197] = {id=197,en="Paragon of Ranger Excellence",ja="果敢なる大狩人"},
    [198] = {id=198,en="Paragon of Dark Knight Excellence",ja="威風なる大暗黒騎士"},
    [199] = {id=199,en="Paragon of Bard Excellence",ja="典麗なる大吟遊詩人"},
    [200] = {id=200,en="Paragon of Samurai Excellence",ja="無双なる大武士"},
    [201] = {id=201,en="Paragon of Dragoon Excellence",ja="勇猛なる大竜騎士"},
    [202] = {id=202,en="Paragon of Ninja Excellence",ja="沈勇なる大忍者"},
    [203] = {id=203,en="Paragon of Summoner Excellence",ja="博雅なる大召喚士"},
    [206] = {id=206,en="New Adventurer",ja="冒険者見習い"},
    [207] = {id=207,en="Certified Adventurer",ja="公認冒険者"},
    [208] = {id=208,en="Shadow Banisher",ja="闇を祓いし者"},
    [209] = {id=209,en="Tried and Tested Knight",ja="騎士の魂宿りし者"},
    [210] = {id=210,en="Dark Sider",ja="暗き業宿りし者"},
    [211] = {id=211,en="The Fanged One",ja="牙持つ者"},
    [212] = {id=212,en="Have Wings, Will Fly",ja="翼持つ者"},
    [213] = {id=213,en="Animal Trainer",ja="モンスター調教師"},
    [214] = {id=214,en="Wandering Minstrel",ja="心の歌うたい"},
    [215] = {id=215,en="Mog's Master",ja="モーグリのご主人さま"},
    [216] = {id=216,en="Mog's Kind Master",ja="やさしいご主人さま"},
    [217] = {id=217,en="Mog's Exceptionally Kind Master",ja="すてきなご主人さま"},
    [218] = {id=218,en="Paragon of Warrior Excellence",ja="勇壮なる大戦士"},
    [219] = {id=219,en="Paragon of Monk Excellence",ja="孤高なる大格闘家"},
    [220] = {id=220,en="Paragon of Red Mage Excellence",ja="比類なき大赤魔道士"},
    [221] = {id=221,en="Paragon of Thief Excellence",ja="華麗なる大盗賊"},
    [222] = {id=222,en="Paragon of Black Mage Excellence",ja="偉大なる大黒魔道士"},
    [223] = {id=223,en="Paragon of White Mage Excellence",ja="高潔なる大白魔道士"},
    [224] = {id=224,en="Mog's Loving Master",ja="ラブラブご主人さま"},
    [226] = {id=226,en="Royal Archer",ja="王国弓兵"},
    [227] = {id=227,en="Royal Spearman",ja="王国槍兵"},
    [228] = {id=228,en="Royal Squire",ja="王国従騎士"},
    [229] = {id=229,en="Royal Swordsman",ja="王国剣士"},
    [230] = {id=230,en="Royal Cavalier",ja="王国騎士"},
    [231] = {id=231,en="Royal Guard",ja="近衛騎士"},
    [232] = {id=232,en="Grand Knight of the Realm",ja="王国大騎士"},
    [233] = {id=233,en="Grand Temple Knight",ja="神殿大騎士"},
    [234] = {id=234,en="Reserve Knight Captain",ja="傭兵騎士団長"},
    [235] = {id=235,en="Elite Royal Guard",ja="上級近衛騎士"},
    [236] = {id=236,en="Legionnaire",ja="共和軍団兵"},
    [237] = {id=237,en="Decurion",ja="十人隊長"},
    [238] = {id=238,en="Centurion",ja="百人隊長"},
    [239] = {id=239,en="Junior Musketeer",ja="准銃士"},
    [240] = {id=240,en="Senior Musketeer",ja="正銃士"},
    [241] = {id=241,en="Musketeer Commander",ja="銃士隊長"},
    [242] = {id=242,en="Gold Musketeer",ja="黄金銃士"},
    [243] = {id=243,en="Praefectus",ja="千人隊長"},
    [244] = {id=244,en="Senior Gold Musketeer",ja="先任黄金銃士"},
    [245] = {id=245,en="Praefectus Castrorum",ja="一番千人隊長"},
    [246] = {id=246,en="Freesword",ja="義勇兵"},
    [247] = {id=247,en="Mercenary",ja="傭兵"},
    [248] = {id=248,en="Mercenary Captain",ja="傭兵隊長"},
    [249] = {id=249,en="Combat Caster",ja="連邦魔戦士"},
    [250] = {id=250,en="Tactician Magician",ja="連邦軍師"},
    [251] = {id=251,en="Wise Wizard",ja="連邦賢者"},
    [252] = {id=252,en="Patriarch Protector",ja="元老院警護隊士"},
    [253] = {id=253,en="Caster Captain",ja="連邦魔戦隊長"},
    [254] = {id=254,en="Master Caster",ja="筆頭魔戦隊長"},
    [255] = {id=255,en="Mercenary Major",ja="連邦傭兵団長"},
    [256] = {id=256,en="Fugitive Minister Bounty Hunter",ja="脱走院長追跡者"},
    [257] = {id=257,en="King of the Opo-opos",ja="オポオポ王"},
    [258] = {id=258,en="Excommunicate of Kazham",ja="カザム追放者"},
    [259] = {id=259,en="Kazham Caller",ja="カザムの客人"},
    [260] = {id=260,en="Dream Dweller",ja="夢の住人"},
    [261] = {id=261,en="Apprentice Sommelier",ja="ソムリエ見習い"},
    [262] = {id=262,en="Desert Hunter",ja="デザートハンター"},
    [263] = {id=263,en="Seeker of Truth",ja="真理を垣間見た者"},
    [264] = {id=264,en="Kuftal Tourist",ja="クフタルツーリスト"},
    [265] = {id=265,en="The Immortal Fisher, Lu Shang",ja="不死身の太公望"},
    [266] = {id=266,en="Looks Sublime in a Subligar",ja="サブリガを輝かせる者"},
    [267] = {id=267,en="Looks Good in Leggings",ja="レギンスを輝かせる者"},
    [268] = {id=268,en="Honorary Doctorate, Majoring in Tonberries",ja="トンベリ博士"},
    [269] = {id=269,en="Treasure-house Ransacker",ja="宝物庫あらし"},
    [270] = {id=270,en="Cracker of the Secret Code",ja="暗号？解読者"},
    [271] = {id=271,en="Black Marketeer",ja="闇ブローカー"},
    [272] = {id=272,en="Acquirer of Ancient Arcanum",ja="古代秘法を継ぐ者"},
    [273] = {id=273,en="Ya Done Good",ja="アンタヤルーニャ"},
    [274] = {id=274,en="Heir of the Great Fire",ja="大いなる火の継承者"},
    [275] = {id=275,en="Heir of the Great Earth",ja="大いなる土の継承者"},
    [276] = {id=276,en="Heir of the Great Water",ja="大いなる水の継承者"},
    [277] = {id=277,en="Heir of the Great Wind",ja="大いなる風の継承者"},
    [278] = {id=278,en="Heir of the Great Ice",ja="大いなる氷の継承者"},
    [279] = {id=279,en="Heir of the Great Lightning",ja="大いなる雷の継承者"},
    [280] = {id=280,en="Guider of Souls to the Sanctuary",ja="聖地に魂導く者"},
    [281] = {id=281,en="Bearer of Bonds Beyond Time",ja="時を越えた絆持つ者"},
    [282] = {id=282,en="Friend of the Opo-opos",ja="オポオポの友"},
    [283] = {id=283,en="Hero on Behalf of Windurst",ja="ウィンダス代表の勇士"},
    [284] = {id=284,en="Victor of the Balga Contest",ja="バルガ武闘会の勝利者"},
    [285] = {id=285,en="Gullible's Travels",ja="いい人カモ"},
    [286] = {id=286,en="Even More Gullible's Travels",ja="もっといい人カモ"},
    [287] = {id=287,en="Heir of the New Moon",ja="新しい力の継承者"},
    [288] = {id=288,en="Assassin Reject",ja="アサシン不採用"},
    [289] = {id=289,en="Black Belt",ja="黒帯の有段者"},
    [290] = {id=290,en="Vermillion Venturer",ja="紅霞の雇われハンター"},
    [291] = {id=291,en="Cerulean Soldier",ja="蒼海の雇われハンター"},
    [292] = {id=292,en="Emerald Exterminator",ja="翠嶺の雇われハンター"},
    [293] = {id=293,en="Guiding Star",ja="導きの星"},
    [294] = {id=294,en="Vestal Chamberlain",ja="魔天のしるべ"},
    [295] = {id=295,en="San d'Orian Royal Heir",ja="次期サンドリア国王候補者"},
    [296] = {id=296,en="Hero Among Heroes",ja="英雄なき時代の英雄"},
    [297] = {id=297,en="Dynamis-San d'Oria Interloper",ja="デュナミス～サンドリアの踏破者"},
    [298] = {id=298,en="Dynamis-Bastok Interloper",ja="デュナミス～バストゥークの踏破者"},
    [299] = {id=299,en="Dynamis-Windurst Interloper",ja="デュナミス～ウィンダスの踏破者"},
    [300] = {id=300,en="Dynamis-Jeuno Interloper",ja="デュナミス～ジュノの踏破者"},
    [301] = {id=301,en="Dynamis-Beaucedine Interloper",ja="デュナミス～ボスディンの踏破者"},
    [302] = {id=302,en="Dynamis-Xarcabard Interloper",ja="デュナミス～ザルカバードの踏破者"},
    [303] = {id=303,en="Discerning Individual",ja="違いの分かるヤツ"},
    [304] = {id=304,en="Very Discerning Individual",ja="とても違いの分かるヤツ"},
    [305] = {id=305,en="Extremely Discerning Individual",ja="とてもとても違いの分かるヤツ"},
    [306] = {id=306,en="Royal Wedding Planner",ja="月下氷人"},
    [307] = {id=307,en="Consort Candidate",ja="サンドリア王子妃候補"},
    [308] = {id=308,en="Obsidian Storm",ja="漆黒の稲妻"},
    [309] = {id=309,en="Pentacide Perpetrator",ja="神威"},
    [310] = {id=310,en="Wood Worshiper",ja="白樫の木彫師"},
    [311] = {id=311,en="Lumber Lather",ja="紫檀の木彫師"},
    [312] = {id=312,en="Accomplished Carpenter",ja="黒檀の木彫師"},
    [313] = {id=313,en="Anvil Advocate",ja="青銅の鍛冶師"},
    [314] = {id=314,en="Forge Fanatic",ja="黒鉄の鍛冶師"},
    [315] = {id=315,en="Accomplished Blacksmith",ja="超鋼の鍛冶師"},
    [316] = {id=316,en="Trinket Turner",ja="真鍮の彫金師"},
    [317] = {id=317,en="Silver Smelter",ja="白銀の彫金師"},
    [318] = {id=318,en="Accomplished Goldsmith",ja="黄金の彫金師"},
    [319] = {id=319,en="Knitting Know-It-All",ja="木綿の裁縫師"},
    [320] = {id=320,en="Loom Lunatic",ja="別珍の裁縫師"},
    [321] = {id=321,en="Accomplished Weaver",ja="錦の裁縫師"},
    [322] = {id=322,en="Formula Fiddler",ja="博識の錬金術師"},
    [323] = {id=323,en="Potion Potentate",ja="神秘の錬金術師"},
    [324] = {id=324,en="Accomplished Alchemist",ja="奇蹟の錬金術師"},
    [325] = {id=325,en="Bone Beautifier",ja="白骨の骨彫師"},
    [326] = {id=326,en="Shell Scrimshander",ja="亀甲の骨彫師"},
    [327] = {id=327,en="Accomplished Boneworker",ja="珊瑚の骨彫師"},
    [328] = {id=328,en="Hide Handler",ja="羊皮の革細工師"},
    [329] = {id=329,en="Leather Lauder",ja="虎皮の革細工師"},
    [330] = {id=330,en="Accomplished Tanner",ja="竜皮の革細工師"},
    [331] = {id=331,en="Fastriver Fisher",ja="川釣りの漁師"},
    [332] = {id=332,en="Coastline Caster",ja="磯釣りの漁師"},
    [333] = {id=333,en="Accomplished Angler",ja="沖釣りの漁師"},
    [334] = {id=334,en="Gourmand Gratifier",ja="炎の調理師"},
    [335] = {id=335,en="Banquet Bestower",ja="三ツ星の調理師"},
    [336] = {id=336,en="Accomplished Chef",ja="至高の調理師"},
    [337] = {id=337,en="Fine Tuner",ja="死ぬ気で冒険者"},
    [338] = {id=338,en="Friend of the Helmed",ja="仮面同盟員"},
    [339] = {id=339,en="Tavnazian Squire",ja="タブナジア侯国騎士見習"},
    [340] = {id=340,en="Ducal Dupe",ja="搾取される弱者"},
    [341] = {id=341,en="Hyper Ultra Sonic Adventurer",ja="翼の名づけ親"},
    [342] = {id=342,en="Rod Retriever",ja="勝訴の支援者"},
    [343] = {id=343,en="Deed Verifier",ja="千骸谷の逃亡者"},
    [344] = {id=344,en="Chocobo Love Guru",ja="チョコボの愛を解いた者"},
    [345] = {id=345,en="Pick-up Artist",ja="ナンパな愛を解いた者"},
    [346] = {id=346,en="Trash Collector",ja="ニィジャンスカルッヘープ"},
    [347] = {id=347,en="Ancient Flame Follower",ja="古のほむらに触れし者"},
    [348] = {id=348,en="Tavnazian Traveler",ja="聖者の島を訪れし者"},
    [349] = {id=349,en="Transient Dreamer",ja="うたかたなる夢を見し者"},
    [350] = {id=350,en="The Lost One",ja="迷いに心揺れし者"},
    [351] = {id=351,en="Treader of an Icy Past",ja="凍てつく過去を踏みしめる者"},
    [352] = {id=352,en="Branded by Lightning",ja="いかづちの洗礼を受けし者"},
    [353] = {id=353,en="Seeker of the Light",ja="眩き世界を求むる者"},
    [354] = {id=354,en="Dead Body",ja="どざえもん"},
    [355] = {id=355,en="Frozen Dead Body",ja="ドザえもん"},
    [356] = {id=356,en="Dreambreaker",ja="夢を断つ者"},
    [357] = {id=357,en="Mist Melter",ja="龍に応える者"},
    [358] = {id=358,en="Delta Enforcer",ja="デルタを狩る者"},
    [359] = {id=359,en="Omega Ostracizer",ja="オメガになる者"},
    [360] = {id=360,en="Ultima Undertaker",ja="アルテマになる者"},
    [361] = {id=361,en="Ulmia's Soulmate",ja="ウルミアの理解者"},
    [362] = {id=362,en="Tenzen's Ally",ja="テンゼンの盟友"},
    [363] = {id=363,en="Companion of Louverance",ja="ルーヴランスの友人"},
    [364] = {id=364,en="True Companion of Louverance",ja="真のルーヴランスの友人"},
    [365] = {id=365,en="Prishe's Buddy",ja="プリッシュの同志"},
    [366] = {id=366,en="Nag'molada's Underling",ja="ナグモラーダのなじみ"},
    [367] = {id=367,en="Esha'ntarl's Comrade in Arms",ja="エシャンタールの戦友"},
    [368] = {id=368,en="The Chebukkis' Worst Nightmare",ja="タルタル3人組の天敵"},
    [369] = {id=369,en="Brown Mage Guinea Pig",ja="はらへにゃー"},
    [370] = {id=370,en="Brown Magic By-Product",ja="はらピーゴロ"},
    [371] = {id=371,en="Bastok's Second Best Dressed",ja="ベスト・オブ・サブリスト"},
    [372] = {id=372,en="Rookie Hero Instructor",ja="冒険初心者の師匠"},
    [373] = {id=373,en="Goblin in Disguise",ja="ゴブリン人間"},
    [374] = {id=374,en="Apostate for Hire",ja="雇われ背信者"},
    [375] = {id=375,en="Talks with Tonberries",ja="残党の標的"},
    [376] = {id=376,en="Rook Buster",ja="ルーク・バスター"},
    [377] = {id=377,en="Banneret",ja="バナレット"},
    [378] = {id=378,en="Gold Balli☆☆☆☆star",ja="ゴールド・バリ☆☆☆☆スター"},
    [379] = {id=379,en="Mythril Balli☆☆☆star",ja="ミスリル・バリ☆☆☆スター"},
    [380] = {id=380,en="Silver Balli☆☆star",ja="シルバー・バリ☆☆スター"},
    [381] = {id=381,en="Bronze Balli☆star",ja="ブロンズ・バリ☆スター"},
    [382] = {id=382,en="Searing★Star",ja="灼熱の★軍星"},
    [383] = {id=383,en="Striking★Star",ja="剛勇の★行星"},
    [384] = {id=384,en="Soothing★Star",ja="白銀の★明星"},
    [385] = {id=385,en="Sable★Star",ja="黒衣の★巨星"},
    [386] = {id=386,en="Scarlet★Star",ja="赤心の★暁星"},
    [387] = {id=387,en="Sonic★Star",ja="疾風の★流星"},
    [388] = {id=388,en="Saintly★Star",ja="名誉の★瑞星"},
    [389] = {id=389,en="Shadowy★Star",ja="無情の★将星"},
    [390] = {id=390,en="Savage★Star",ja="百獣の★群星"},
    [391] = {id=391,en="Singing★Star",ja="博愛の★極星"},
    [392] = {id=392,en="Sniping★Star",ja="神速の★彗星"},
    [393] = {id=393,en="Slicing★Star",ja="万夫の★魁星"},
    [394] = {id=394,en="Sneaking★Star",ja="雲影の★妖星"},
    [395] = {id=395,en="Spearing★Star",ja="竜座の★双星"},
    [396] = {id=396,en="Summoning★Star",ja="夢幻の★遊星"},
    [397] = {id=397,en="Putrid Purveyor of Pungent Petals",ja="ちょっと臭う人"},
    [398] = {id=398,en="Unquenchable Light",ja="花散る嵐起こす者"},
    [399] = {id=399,en="Ballistager",ja="バリステイジャー"},
    [400] = {id=400,en="Ultimate Champion of the World",ja="天下無双魔阿斗戦覇者"},
    [401] = {id=401,en="Warrior of the Crystal",ja="クリスタルの戦士"},
    [402] = {id=402,en="Indomitable Fisher",ja="釣神流免許皆伝"},
    [403] = {id=403,en="Averter of the Apocalypse",ja="世界の終わりを繰る者"},
    [404] = {id=404,en="Banisher of Emptiness",ja="虚ろなる闇に涙する者"},
    [405] = {id=405,en="Random Adventurer",ja="適当な冒険者"},
    [406] = {id=406,en="Irresponsible Adventurer",ja="いい加減な冒険者"},
    [407] = {id=407,en="Odorous Adventurer",ja="生臭冒険者"},
    [408] = {id=408,en="Insignificant Adventurer",ja="歌う価値もない冒険者"},
    [409] = {id=409,en="Final Balli☆☆☆☆star",ja="ファイナバリ☆☆☆☆スター"},
    [410] = {id=410,en="Balli☆☆☆☆star Royale",ja="バリ☆☆☆☆スター・ロワイヤル"},
    [411] = {id=411,en="Destined Fellow",ja="導となる者"},
    [412] = {id=412,en="Orcish Serjeant",ja="オーキシュサージェント"},
    [413] = {id=413,en="Bronze Quadav",ja="ブロンズクゥダフ"},
    [414] = {id=414,en="Yagudo Initiate",ja="ヤグードイニシエート"},
    [415] = {id=415,en="Moblin Kinsman",ja="モブリンキンズマン"},
    [416] = {id=416,en="Sin Hunter Hunter",ja="決闘の勝利者"},
    [417] = {id=417,en="Disciple of Justice",ja="正義の勝利者"},
    [418] = {id=418,en="Monarch Linn Patrol Guard",ja="帝龍の飛泉調査員"},
    [419] = {id=419,en="Team Player",ja="志を共にせし者"},
    [420] = {id=420,en="Worthy of Trust",ja="心の糧となりし者"},
    [421] = {id=421,en="Conqueror of Fate",ja="人の系譜を開く者"},
    [422] = {id=422,en="Breaker of the Chains",ja="呪縛を葬りし者"},
    [423] = {id=423,en="A Friend Indeed",ja="助け合う者"},
    [424] = {id=424,en="Heir to the Realm of Dreams",ja="夢渡る力の継承者"},
    [425] = {id=425,en="Gold Hook",ja="ゴールドフック"},
    [426] = {id=426,en="Mythril Hook",ja="ミスリルフック"},
    [427] = {id=427,en="Silver Hook",ja="シルバーフック"},
    [428] = {id=428,en="Copper Hook",ja="カッパーフック"},
    [430] = {id=430,en="Dynamis-Valkurm Interloper",ja="デュナミス～バルクルムの踏破者"},
    [431] = {id=431,en="Dynamis-Buburimu Interloper",ja="デュナミス～ブブリムの踏破者"},
    [432] = {id=432,en="Dynamis-Qufim Interloper",ja="デュナミス～クフィムの踏破者"},
    [433] = {id=433,en="Dynamis-Tavnazia Interloper",ja="デュナミス～タブナジアの踏破者"},
    [434] = {id=434,en="Confronter of Nightmares",ja="悪夢ヲ喰らい合ウ者"},
    [435] = {id=435,en="Disturber of Slumber",ja="目覚めしかんなぎ"},
    [436] = {id=436,en="Interrupter of Dreams",ja="眠り浅きまれびと"},
    [437] = {id=437,en="Sapphire★Star",ja="青雲の★客星"},
    [438] = {id=438,en="Surging★Star",ja="四海の★奔星"},
    [439] = {id=439,en="Swaying★Star",ja="志操の★連星"},
    [440] = {id=440,en="Dark Resistant",ja="冥闇への抵抗者"},
    [441] = {id=441,en="Bearer of the Mark of Zahak",ja="双頭蛇の印背負いしモノ"},
    [442] = {id=442,en="Seagull Phratrie Crew Member",ja="海猫党クルー"},
    [443] = {id=443,en="Proud Automaton Owner",ja="からくりオーナー"},
    [444] = {id=444,en="Private Second Class",ja="山猫二等傭兵"},
    [445] = {id=445,en="Private First Class",ja="山猫一等傭兵"},
    [446] = {id=446,en="Superior Private",ja="山猫上等傭兵"},
    [447] = {id=447,en="Wildcat Publicist",ja="山猫宣伝員"},
    [448] = {id=448,en="Adamantking Usurper",ja="アダマントキング　ユザーパー"},
    [449] = {id=449,en="Overlord Overthrower",ja="オーバーロード　オーバースロワー"},
    [450] = {id=450,en="Deity Debunker",ja="デイティーデバンカー"},
    [451] = {id=451,en="Fafnir Slayer",ja="ファヴニル　スレーヤー"},
    [452] = {id=452,en="Aspidochelone Sinker",ja="アスピドケロン　シンカー"},
    [453] = {id=453,en="Nidhogg Slayer",ja="ニーズヘッグ　スレーヤー"},
    [454] = {id=454,en="Maat Masher",ja="マート　マッシャー"},
    [455] = {id=455,en="Kirin Captivator",ja="キリン　キャプティヴェイター"},
    [456] = {id=456,en="Cactrot Desacelerador",ja="カクトロット　デサセレラドール"},
    [457] = {id=457,en="Lifter of Shadows",ja="リフター　オブ　シャドーズ"},
    [458] = {id=458,en="Tiamat Trouncer",ja="ティアマット　トラウンサー"},
    [459] = {id=459,en="Vrtra Vanquisher",ja="ヴリトラ　ヴァンクィシャー"},
    [460] = {id=460,en="World Serpent Slayer",ja="ワールドサーペントスレーヤー"},
    [461] = {id=461,en="Xolotl Xtrapolator",ja="ショロトル　エクストラポレーター"},
    [462] = {id=462,en="Boroka Beleaguerer",ja="ボロカ　ベリーガラー"},
    [463] = {id=463,en="Ouryu Overwhelmer",ja="應龍調伏猛士"},
    [464] = {id=464,en="Vinegar Evaporator",ja="ビネガーエヴァポレーター"},
    [465] = {id=465,en="Virtuous Saint",ja="ヴァーチャスセイント"},
    [466] = {id=466,en="Bye-bye, Taisai",ja="さよなら太歳"},
    [467] = {id=467,en="Temenos Liberator",ja="テメナスリバレーター"},
    [468] = {id=468,en="Apollyon Ravager",ja="アポリオンラベジャー"},
    [469] = {id=469,en="Wyrm Astonisher",ja="ウィルムアストニシャー"},
    [470] = {id=470,en="Nightmare Awakener",ja="ナイトメア　アウェイクナー"},
    [471] = {id=471,en="Cerberus Muzzler",ja="ケルベロスマズラー"},
    [472] = {id=472,en="Hydra Headhunter",ja="ハイドラヘッドハンター"},
    [473] = {id=473,en="Shining Scale Rifler",ja="スケールライフラー"},
    [474] = {id=474,en="Troll Subjugator",ja="トロールサブジュゲーター"},
    [475] = {id=475,en="Gorgonstone Sunderer",ja="ゴーゴンストーンサンダラー"},
    [476] = {id=476,en="Khimaira Carver",ja="キマイラカーバー"},
    [477] = {id=477,en="Elite Einherjar",ja="エインヘリヤルエリート"},
    [478] = {id=478,en="Star Charioteer",ja="スターチャリオッティア"},
    [479] = {id=479,en="Sun Charioteer",ja="サンチャリオッティア"},
    [480] = {id=480,en="Subduer of the Mamool Ja",ja="マムークサブドゥア"},
    [481] = {id=481,en="Subduer of the Trolls",ja="ハルブーンサブドゥア"},
    [482] = {id=482,en="Subduer of the Undead Swarm",ja="アンデッドサブドゥア"},
    [483] = {id=483,en="Agent of the Allied Forces",ja="アルタナ同盟エージェント"},
    [484] = {id=484,en="Scenic Snapshotter",ja="風景記録の達人"},
    [485] = {id=485,en="Branded by the Five Serpents",ja="五蛇の烙印押されしモノ"},
    [486] = {id=486,en="Immortal Lion",ja="蒼き獅子"},
    [487] = {id=487,en="Paragon of Blue Mage Excellence",ja="冷厳なる大青魔道士"},
    [488] = {id=488,en="Paragon of Corsair Excellence",ja="剛胆なる大海賊"},
    [489] = {id=489,en="Paragon of Puppetmaster Excellence",ja="痛快なる大からくり士"},
    [490] = {id=490,en="Lance Corporal",ja="山猫傭兵長"},
    [491] = {id=491,en="Corporal",ja="山猫伍長"},
    [492] = {id=492,en="Master of Ambition",ja="慧眼を断つモノ"},
    [493] = {id=493,en="Master of Chance",ja="碧海の勝負師"},
    [494] = {id=494,en="Master of Manipulation",ja="奔放不羈の業人"},
    [495] = {id=495,en="Ovjang's Errand Runner",ja="アヴゼンの小間使い"},
    [496] = {id=496,en="Sergeant",ja="山猫軍曹"},
    [497] = {id=497,en="Sergeant Major",ja="山猫曹長"},
    [498] = {id=498,en="Karababa's Tour Guide",ja="カラババの現地ガイド"},
    [499] = {id=499,en="Karababa's Bodyguard",ja="カラババのボディガード"},
    [500] = {id=500,en="Karababa's Secret Agent",ja="カラババの特命エージェント"},
    [501] = {id=501,en="Skyserpent Aggrandizer",ja="天蛇将の遊撃隊"},
    [502] = {id=502,en="Chief Sergeant",ja="山猫特務曹長"},
    [503] = {id=503,en="Aphmau's Mercenary",ja="アフマウの傭兵"},
    [504] = {id=504,en="Nashmeira's Mercenary",ja="ナシュメラの傭兵"},
    [505] = {id=505,en="Chocorookie",ja="チョコボレースのルーキー"},
    [506] = {id=506,en="Second Lieutenant",ja="山猫少尉"},
    [507] = {id=507,en="Galeserpent Guardian",ja="風蛇将の教導隊"},
    [508] = {id=508,en="Stoneserpent Shocktrooper",ja="土蛇将の突撃隊"},
    [509] = {id=509,en="Photopticator Operator",ja="バラカフ発明品の使い手"},
    [510] = {id=510,en="Salaheem's Risk Assessor",ja="サラヒムの斥候"},
    [511] = {id=511,en="Treasure Trove Tender",ja="財宝の番兵"},
    [512] = {id=512,en="Gessho's Mercy",ja="月照の介錯人"},
    [513] = {id=513,en="Emissary of the Empress",ja="聖皇の密使"},
    [514] = {id=514,en="Endymion Paratrooper",ja="エンディミオン空艇隊員"},
    [515] = {id=515,en="Naja's Comrade-In-Arms",ja="ナジャの戦友"},
    [516] = {id=516,en="Nashmeira's Loyalist",ja="ナシュメラの腹心"},
    [517] = {id=517,en="Preventer of Ragnarok",ja="ラグナロクの調停者"},
    [518] = {id=518,en="Champion of Aht Urhgan",ja="アトルガンの守護者"},
    [519] = {id=519,en="First Lieutenant",ja="山猫中尉"},
    [520] = {id=520,en="Captain",ja="山猫大尉"},
    [521] = {id=521,en="Crystal Stakes Cupholder",ja="クリスタルステークス覇者"},
    [522] = {id=522,en="Winning Owner",ja="勝鳥オーナー"},
    [523] = {id=523,en="Victorious Owner",ja="猛鳥オーナー"},
    [524] = {id=524,en="Triumphant Owner",ja="覇鳥オーナー"},
    [525] = {id=525,en="High Roller",ja="幸運の勝負師"},
    [526] = {id=526,en="Fortune's Favorite",ja="強運の勝負師"},
    [527] = {id=527,en="Superhero",ja="スーパーヒーロー"},
    [528] = {id=528,en="Superheroine",ja="スーパーヒロイン"},
    [529] = {id=529,en="Bloody Berserker",ja="ブラッディバーサーカー"},
    [530] = {id=530,en="The Sixth Serpent",ja="准蛇将"},
    [531] = {id=531,en="Eternal Mercenary",ja="エターナルマーシナリー"},
    [532] = {id=532,en="Springserpent Sentry",ja="水蛇将の親衛隊"},
    [533] = {id=533,en="Sprightly★Star",ja="魅惑の★眩星"},
    [534] = {id=534,en="Sagacious★Star",ja="明哲の★識星"},
    [535] = {id=535,en="Schultz Scholar",ja="見習い軍学者"},
    [536] = {id=536,en="Knight of the Iron Ram",ja="鉄羊騎士"},
    [537] = {id=537,en="Fourth Division Soldier",ja="第四共和軍団兵"},
    [538] = {id=538,en="Cobra Unit Mercenary",ja="コブラ傭兵"},
    [539] = {id=539,en="Windtalker",ja="舞台裏の目撃者"},
    [540] = {id=540,en="Lady Killer",ja="レディキラー"},
    [541] = {id=541,en="Troupe Brilioth Dancer",ja="ブリリオート舞踏団ダンサー"},
    [542] = {id=542,en="Cait Sith's Assistant",ja="ケット・シーの助手"},
    [543] = {id=543,en="Ajido-Marujido's Minder",ja="アジドマルジドの救世主"},
    [544] = {id=544,en="Comet Charioteer",ja="コメットチャリオッティア"},
    [545] = {id=545,en="Moon Charioteer",ja="ムーンチャリオッティア"},
    [546] = {id=546,en="Sandworm Wrangler",ja="サンドウォームキャッチャー"},
    [547] = {id=547,en="Ixion Hornbreaker",ja="イクシオンホーンブレイカー"},
    [548] = {id=548,en="Lambton Worm Desegmenter",ja="ラムトンウォームデセグメンター"},
    [549] = {id=549,en="Pandemonium Queller",ja="パンデモニウムクウェラー"},
    [550] = {id=550,en="Debaser of Dynasties",ja="ダイナスティディベーサー"},
    [551] = {id=551,en="Disperser of Darkness",ja="ダークネスディスパーサー"},
    [552] = {id=552,en="Ender of Idolatry",ja="アイドラトリーエンダー"},
    [553] = {id=553,en="Lugh Exorcist",ja="ルー　エクソシスト"},
    [554] = {id=554,en="Elatha Exorcist",ja="エラサ　エクソシスト"},
    [555] = {id=555,en="Ethniu Exorcist",ja="エスニウ　エクソシスト"},
    [556] = {id=556,en="Tethra Exorcist",ja="テスラ　エクソシスト"},
    [557] = {id=557,en="Buarainech Exorcist",ja="ブーリンナク　エクソシスト"},
    [558] = {id=558,en="Oupire Impaler",ja="ウピール　インペーラー"},
    [559] = {id=559,en="Scylla Skinner",ja="スキュラ　スキンナー"},
    [560] = {id=560,en="Zirnitra Wingclipper",ja="ジルニトラ　ウィングクリッパー"},
    [561] = {id=561,en="Dawon Trapper",ja="ドゥントラッパー"},
    [562] = {id=562,en="Krabkatoa Steamer",ja="クラブカタウ　スチーマー"},
    [563] = {id=563,en="Orcus Trophy Hunter",ja="オルクス　トロフィーハンター"},
    [564] = {id=564,en="Blobdingnag Burster",ja="ブロブディンナグ　バースター"},
    [565] = {id=565,en="Verthandi Ensnarer",ja="ヴェルザンディ　エンスネアラー"},
    [566] = {id=566,en="Ruthven Entomber",ja="ルスベン　エントゥーマー"},
    [567] = {id=567,en="Yilbegan Hideflayer",ja="イルベガン　ハイドフレーヤー"},
    [568] = {id=568,en="Torchbearer of the 1st Walk",ja="第1ウォークのトーチベアラー"},
    [569] = {id=569,en="Torchbearer of the 2nd Walk",ja="第2ウォークのトーチベアラー"},
    [570] = {id=570,en="Torchbearer of the 3rd Walk",ja="第3ウォークのトーチベアラー"},
    [571] = {id=571,en="Torchbearer of the 4th Walk",ja="第4ウォークのトーチベアラー"},
    [572] = {id=572,en="Torchbearer of the 5th Walk",ja="第5ウォークのトーチベアラー"},
    [573] = {id=573,en="Torchbearer of the 6th Walk",ja="第6ウォークのトーチベアラー"},
    [574] = {id=574,en="Torchbearer of the 7th Walk",ja="第7ウォークのトーチベアラー"},
    [575] = {id=575,en="Torchbearer of the 8th Walk",ja="第8ウォークのトーチベアラー"},
    [576] = {id=576,en="Furniture Store Owner",ja="ファーニチャーストアオーナー"},
    [577] = {id=577,en="Armory Owner",ja="アーモリーオーナー"},
    [578] = {id=578,en="Jewelry Store Owner",ja="ジュエリーストアオーナー"},
    [579] = {id=579,en="Boutique Owner",ja="ブティックオーナー"},
    [580] = {id=580,en="Apothecary Owner",ja="アポケサリオーナー"},
    [581] = {id=581,en="Curiosity Shop Owner",ja="キュリオシティショップオーナー"},
    [582] = {id=582,en="Shoeshop Owner",ja="シューショップオーナー"},
    [583] = {id=583,en="Fishmonger Owner",ja="フィッシュモンガーオーナー"},
    [584] = {id=584,en="Restaurant Owner",ja="レストランオーナー"},
    [585] = {id=585,en="Assistant Detective",ja="ミスリル銃士隊探偵助手"},
    [586] = {id=586,en="Promising Dancer",ja="才気あるダンサー"},
    [587] = {id=587,en="Stardust Dancer",ja="星くずのダンサー"},
    [588] = {id=588,en="Elegant Dancer",ja="流麗なる大舞踏家"},
    [589] = {id=589,en="Dazzling Dance Diva",ja="輝く星の踊り子"},
    [590] = {id=590,en="Friend of Lehko Habhoka",ja="レコ・ハボッカの友人"},
    [591] = {id=591,en="Summa Cum Laude",ja="聡明なる大学者"},
    [592] = {id=592,en="Grimoire Bearer",ja="グリモアを継ぐもの"},
    [593] = {id=593,en="Seasoning Connoisseur",ja="塩ソムリエ"},
    [594] = {id=594,en="Fine Young Griffon",ja="少年騎士団のエース"},
    [595] = {id=595,en="Babban's Traveling Companion",ja="ウェイレアの旅の仲間"},
    [596] = {id=596,en="Fellow Fortifier",ja="高め合う者"},
    [597] = {id=597,en="Chocochampion",ja="チョコボレースのホープ"},
    [598] = {id=598,en="Traverser of Time",ja="往代を巡りし者"},
    [599] = {id=599,en="Mythril Musketeer No. 6",ja="ミスリル銃士隊No.6"},
    [600] = {id=600,en="Jewel of the Cobra Unit",ja="コブラ傭兵団の秘蔵っ子"},
    [601] = {id=601,en="Knight of the Swiftwing Griffin",ja="鷲獅子騎士"},
    [602] = {id=602,en="Wyrmsworn Protector",ja="気高き龍の盟友"},
    [603] = {id=603,en="Flameserpent Facilitator",ja="炎蛇将の特攻隊"},
    [604] = {id=604,en="Maze Wanderer",ja="迷宮を彷徨う者"},
    [605] = {id=605,en="Maze Navigator",ja="迷宮を行交う者"},
    [606] = {id=606,en="Maze Scholar",ja="迷宮を知る者"},
    [607] = {id=607,en="Maze Artisan",ja="迷宮を創る者"},
    [608] = {id=608,en="Maze Overlord",ja="迷宮を統べる者"},
    [609] = {id=609,en="Swarminator",ja="スウォーミネーター"},
    [610] = {id=610,en="Battle of Jeuno Veteran",ja="ジュノ攻防戦の功労者"},
    [611] = {id=611,en="Grand Greedalox",ja="ゴウツバクリ"},
    [612] = {id=612,en="Karaha-Baruha's Research Assistant",ja="隠者の協力者"},
    [613] = {id=613,en="Honorary Knight of the Cardinal Stag",ja="赤鹿の名誉騎士"},
    [614] = {id=614,en="Detector of Deception",ja="仮面を砕きし者"},
    [615] = {id=615,en="Silencer of the Echo",ja="神の頌歌に返せる者"},
    [616] = {id=616,en="Bestrider of Futures",ja="境界に生きる者"},
    [617] = {id=617,en="Mog House Handyperson",ja="モグハウス・キーパー"},
    [618] = {id=618,en="Presidential Protector",ja="真実を追う者"},
    [619] = {id=619,en="The Moon's Companion",ja="星月に寄り添う者"},
    [620] = {id=620,en="Arrester of the Ascension",ja="シャントット帝国反乱分子"},
    [621] = {id=621,en="House Aurchiat Retainer",ja="伯爵家の客分"},
    [622] = {id=622,en="Wanderer of Time",ja="失はれた者"},
    [623] = {id=623,en="Smiter of the Shadow",ja="シャドウスマイター"},
    [624] = {id=624,en="Heir of the Blessed Radiance",ja="大いなる天光の継承者"},
    [625] = {id=625,en="Heir of the Blighted Gloom",ja="大いなる冥闇の継承者"},
    [626] = {id=626,en="Sworn to the Dark Divinity",ja="冥路の騎士"},
    [627] = {id=627,en="Temperer of Mythril",ja="ミスリル銃士隊No.0"},
    [628] = {id=628,en="Star in the Azure Sky",ja="蒼天のしるべ"},
    [629] = {id=629,en="Fangmonger Forestaller",ja="コロッサスデストロイヤー"},
    [630] = {id=630,en="Visitor to Abyssea",ja="異界の訪問者"},
    [631] = {id=631,en="Friend of Abyssea",ja="異界の協力者"},
    [632] = {id=632,en="Warrior of Abyssea",ja="異界の戦士"},
    [633] = {id=633,en="Stormer of Abyssea",ja="異界の強襲者"},
    [634] = {id=634,en="Devastator of Abyssea",ja="異界の破壊者"},
    [635] = {id=635,en="Hero of Abyssea",ja="異界の勇者"},
    [636] = {id=636,en="Champion of Abyssea",ja="異界の英雄"},
    [637] = {id=637,en="Conqueror of Abyssea",ja="異界の覇者"},
    [638] = {id=638,en="Savior of Abyssea",ja="異界の救世主"},
    [639] = {id=639,en="Vanquisher of Spite",ja="盤上の覇者"},
    [640] = {id=640,en="Hadhayosh Halterer",ja="ハダヨッシュホルタラー"},
    [641] = {id=641,en="Briareus Feller",ja="ブリアレオスフェラー"},
    [642] = {id=642,en="Karkinos Clawcrusher",ja="カルキノスクロークラッシャー"},
    [643] = {id=643,en="Carabosse Quasher",ja="カラボスクワッシャー"},
    [644] = {id=644,en="Ovni Obliterator",ja="オヴニオブリテレイター"},
    [645] = {id=645,en="Ruminator Confounder",ja="ルミネイターコンファウンダー"},
    [646] = {id=646,en="Eccentricity Expunger",ja="エクセントリセティエクスパンジャー"},
    [647] = {id=647,en="Fistule Drainer",ja="フィスチュルドレイナー"},
    [648] = {id=648,en="Kukulkan Defanger",ja="ククルカンデファンガー"},
    [649] = {id=649,en="Turul Grounder",ja="トゥルルグラウンダー"},
    [650] = {id=650,en="Bloodeye Banisher",ja="ブラッドアイバニッシャー"},
    [651] = {id=651,en="Satiator Depriver",ja="セイシエーターデプライバー"},
    [652] = {id=652,en="Iratham Capturer",ja="イラタムキャプチャラー"},
    [653] = {id=653,en="Lacovie Capsizer",ja="ラコビキャプサイザー"},
    [654] = {id=654,en="Chloris Uprooter",ja="クロリスアップルーター"},
    [655] = {id=655,en="Myrmecoleon Tamer",ja="メルメコレオンテイマー"},
    [656] = {id=656,en="Glavoid Stampeder",ja="グラヴォイドスタンピーダー"},
    [657] = {id=657,en="Usurper Deposer",ja="ユーサーパーデポーザー"},
    [658] = {id=658,en="Yaanei Crasher",ja="ヤーネイ　クラッシャー"},
    [659] = {id=659,en="Kutharei Unhorser",ja="クタレイ　アンホーサー"},
    [660] = {id=660,en="Sippoy Capturer",ja="シポイ　キャプチャラー"},
    [661] = {id=661,en="Titlacauan Dismemberer",ja="ティトラカワン　ディスメンベラー"},
    [662] = {id=662,en="Smok Defogger",ja="ズモク　ディフォッガー"},
    [663] = {id=663,en="Amhuluk Inundater",ja="アムルック　イナンデーター"},
    [664] = {id=664,en="Pulverizer Dismantler",ja="パルバライザー　ディスマンテラー"},
    [665] = {id=665,en="Durinn Deceiver",ja="ドゥリン　ディシーバー"},
    [666] = {id=666,en="Karkadann Exoculator",ja="カーカダン　エクスオキュレーター"},
    [667] = {id=667,en="Ulhuadshi Desiccator",ja="ウルハドシ　デシケーター"},
    [668] = {id=668,en="Itzpapalotl Declawer",ja="イツパパロツル　ディクローアー"},
    [669] = {id=669,en="Sobek Mummifier",ja="ソベク　マミファイアー"},
    [670] = {id=670,en="Cirein-croin Harpooner",ja="キレイン・キロイン　ハープーナー"},
    [671] = {id=671,en="Bukhis Tetherer",ja="ブッキス　テザラー"},
    [672] = {id=672,en="Sedna Tuskbreaker",ja="セドナ　タスクブレーカー"},
    [673] = {id=673,en="Cleaver Dismantler",ja="クリーバー　ディスマンテラー"},
    [674] = {id=674,en="Executioner Dismantler",ja="エクセキュショナー　ディスマンテラー"},
    [675] = {id=675,en="Severer Dismantler",ja="セバラー　ディスマンテラー"},
    [676] = {id=676,en="Lusca Debunker",ja="ルスカ　ディバンカー"},
    [677] = {id=677,en="Tristitia Deliverer",ja="トリスティシア　デリバラー"},
    [678] = {id=678,en="Ketea Beacher",ja="ケテア　ビーチャー"},
    [679] = {id=679,en="Rani Decrowner",ja="ラーニー　デクラウナー"},
    [680] = {id=680,en="Orthrus Decapitator",ja="オルトロス　デカピテーター"},
    [681] = {id=681,en="Dragua Slayer",ja="ドラグア　スレイヤー"},
    [682] = {id=682,en="Bennu Deplumer",ja="ベンヌ　デプルーマー"},
    [683] = {id=683,en="Hedjedjet Destinger",ja="ヘデデット　デスティンガー"},
    [684] = {id=684,en="Cuijatender Desiccator",ja="クイジャテンダー　デシケイター"},
    [685] = {id=685,en="Brulo Extinguisher",ja="ブルーロ　エクスティングイシャー"},
    [686] = {id=686,en="Pantokrator Disprover",ja="パントクラトル　ディスプルーバー"},
    [687] = {id=687,en="Apademak Annihilator",ja="アペデマク　アナイアレーター"},
    [688] = {id=688,en="Isgebind Defroster",ja="イスゲビンド　デフロスター"},
    [689] = {id=689,en="Resheph Eradicator",ja="レシェフ　エラディケイター"},
    [690] = {id=690,en="Empousa Expurgator",ja="エンプーサ　エクスパーゲイター"},
    [691] = {id=691,en="Indrik Immolator",ja="インドリック　イモレイター"},
    [692] = {id=692,en="Ogopogo Overturner",ja="オゴポゴ　オウバーターナー"},
    [693] = {id=693,en="Raja Regicide",ja="ラージャー　レジサイド"},
    [694] = {id=694,en="Alfard Detoxifier",ja="アルファルド　デトックシファイアー"},
    [695] = {id=695,en="Azdaja Abolisher",ja="アジュダヤ　アボリシャー"},
    [696] = {id=696,en="Amphitrite Shucker",ja="アムピトリーテー　シャッカー"},
    [697] = {id=697,en="Fuath Purifier",ja="フーア　ピュリファイアー"},
    [698] = {id=698,en="Killakriq Excoriator",ja="キラクリック　エクスコリエイター"},
    [699] = {id=699,en="Maere Bestirrer",ja="メーア　ベスターラー"},
    [700] = {id=700,en="Wyrm God Defier",ja="神竜を葬りし者"},
    [701] = {id=701,en="Hahava Condemner",ja="ハハヴァ　コンデンマー"},
    [702] = {id=702,en="Celaeno Silencer",ja="セラエノ　サイレンサー"},
    [703] = {id=703,en="Voidwrought Deconstructor",ja="ヴォイドロート　デコンストラクター"},
    [704] = {id=704,en="Devourer of Shadows",ja="デバウアー　オブ　シャドーズ"},
    [705] = {id=705,en="Kaggen Clobberer",ja="カッゲン　クロッバラー"},
    [706] = {id=706,en="Akvan Absterger",ja="アクヴァン　アブスタージャー"},
    [707] = {id=707,en="Pil Unfrocker",ja="フィル　アンフロッカー"},
    [708] = {id=708,en="Qilin Contravener",ja="チーリン　コントラビーナー"},
    [709] = {id=709,en="Uptala Reprobator",ja="ウプタラ　レプロベーター"},
    [710] = {id=710,en="Aello Abator",ja="アイエロ　アベイター"},
    [711] = {id=711,en="Torchbearer of the 9th Walk",ja="第9ウォークのトーチベアラー"},
    [712] = {id=712,en="Torchbearer of the 10th Walk",ja="第10ウォークのトーチベアラー"},
    [713] = {id=713,en="Torchbearer of the 11th Walk",ja="第11ウォークのトーチベアラー"},
    [714] = {id=714,en="Nightmare Illuminator",ja="ナイトメア　イルミネーター"},
    [715] = {id=715,en="Gaunab Gutter",ja="ガウナブ　ガッター"},
    [716] = {id=716,en="Kalasutrax Cremator",ja="カラストラクス　クリーメーター"},
    [717] = {id=717,en="Ocythoe Overrider",ja="オシトエ　オバーライダー"},
    [718] = {id=718,en="Ig-Alima Inhumer",ja="イッグ・アリマ　インヒューマー"},
    [719] = {id=719,en="Botulus Rex Engorger",ja="ボチュルス・レックス　エンゴージャー"},
    [720] = {id=720,en="Torchbearer of the 12th Walk",ja="第12ウォークのトーチベアラー"},
    [721] = {id=721,en="Torchbearer of the 13th Walk",ja="第13ウォークのトーチベアラー"},
    [722] = {id=722,en="Torchbearer of the 14th Walk",ja="第14ウォークのトーチベアラー"},
    [723] = {id=723,en="Torchbearer of the 15th Walk",ja="第15ウォークのトーチベアラー"},
    [724] = {id=724,en="Delver of the Depths",ja="未踏領域を踏破せし者"},
    [725] = {id=725,en="Subjugator of the Lofty",ja="ロフティレギオン　サブジュゲーター"},
    [726] = {id=726,en="Subjugator of the Mired",ja="マイアーレギオン　サブジュゲーター"},
    [727] = {id=727,en="Subjugator of the Soaring",ja="ソアリングレギオン　サブジュゲーター"},
    [728] = {id=728,en="Subjugator of the Veiled",ja="ベールレギオン　サブジュゲーター"},
    [729] = {id=729,en="Legendary Legionnaire",ja="パラマウントレギオン　サブジュゲーター"},
    [730] = {id=730,en="Witness to Provenance",ja="原初の輝きに触れし者"},
    [731] = {id=731,en="Bismarck Flenser",ja="ビスマルク　フレンサー"},
    [732] = {id=732,en="Morta Extirpator",ja="モルタ　エクスターペイター"},
    [733] = {id=733,en="Unsung Heroine",ja="アンサングヒロイン"},
    [734] = {id=734,en="Epic Heroine",ja="エピックヒロイン"},
    [735] = {id=735,en="Epic Einherjar",ja="エインヘリヤルエピック"},
    [736] = {id=736,en="Mender of Wings",ja="翼を抱きし者"},
    [737] = {id=737,en="Champion of the Dawn",ja="アルタナの神兵"},
    [738] = {id=738,en="Bushin Aspirant",ja="武神の門出に立つ者"},
    [739] = {id=739,en="Bushin-Ryu Inheritor",ja="武神流免許皆伝"},
    [740] = {id=740,en="Temenos Emancipator",ja="テメナスエマンシペーター"},
    [741] = {id=741,en="Apollyon Razer",ja="アポリオンレイザー"},
    [742] = {id=742,en="Goldwing Squasher",ja="ゴールドウィング　スクァッシャー"},
    [743] = {id=743,en="Silagilith Detonator",ja="サイレジャリス　デトネーター"},
    [744] = {id=744,en="Surtr Smotherer",ja="スルト　スマザラー"},
    [745] = {id=745,en="Dreyruk Predominator",ja="ドレールック　プレドミネーター"},
    [746] = {id=746,en="Samursk Vitiator",ja="サムルスク　ビティエター"},
    [747] = {id=747,en="Umagrhk Manemangler",ja="ウマゲルク　メーンマングラー"},
    [748] = {id=748,en="Supernal Savant",ja="スパーナルサバント"},
    [749] = {id=749,en="Solar Sage",ja="ソーラーセージ"},
    [750] = {id=750,en="Bolide Baron",ja="ボライドバロン"},
    [751] = {id=751,en="Moon Maven",ja="ムーンメーヴェン"},
    [752] = {id=752,en="Izyx Vexer",ja="イジックス　ヴェックサー"},
    [753] = {id=753,en="Grannus Garroter",ja="グランナス　ガロッター"},
    [754] = {id=754,en="Svaha Striker",ja="スヴァッハ　ストライカー"},
    [755] = {id=755,en="Melisseus Domesticator",ja="メリシアス　ドメステケイター"},
    [756] = {id=756,en="Waterway Exemplar",ja="ウォーターウェー　エグゼンプラー"},
    [757] = {id=757,en="Cavern Exemplar",ja="カーヴァン　エグゼンプラー"},
    [758] = {id=758,en="Muyingwa Wingcrusher",ja="ムイングワ　ウイングクラッシャー"},
    [759] = {id=759,en="Dakuwaqa Trawler",ja="ダクワカ　トローラー"},
    [760] = {id=760,en="Tojil Douser",ja="トヒル　ダウザー"},
    [761] = {id=761,en="Colkhab Dethroner",ja="コルカブ　デスローナー"},
    [762] = {id=762,en="Achuka Glaciator",ja="アチュカ　グレイシエイター"},
    [763] = {id=763,en="Tchakka Desiccator",ja="チャッカ　デシケイター"},
    [764] = {id=764,en="Weald Exemplar",ja="ウィールド　エグゼンプラー"},
    [765] = {id=765,en="Hurkan Birdlimeist",ja="フルカン　バードライミスト"},
    [766] = {id=766,en="Yumcax Logger",ja="ユムカクス　ローガー"},
    [767] = {id=767,en="Colkhab Hivecrusher",ja="コルカブ　ハイヴクラッシャー"},
    [768] = {id=768,en="Achuka Coagulator",ja="アチュカ　コアギュレイター"},
    [769] = {id=769,en="Tchakka Filleter",ja="チャッカ　フィレーヤー"},
    [770] = {id=770,en="Rabbit Tussler",ja="ラビット　タッスラー"},
    [771] = {id=771,en="Helminth Mincer",ja="ヘルミンス　ミンサー"},
    [772] = {id=772,en="Mandragardener",ja="マンドラ　ガーデナー"},
    [773] = {id=773,en="Moppet Massacrer",ja="モペット　マサカーラー"},
    [774] = {id=774,en="Rip-roaring Limbrender",ja="ローリング　リムレンダー"},
    [775] = {id=775,en="Shell Shocker",ja="シェル　ショッカー"},
    [776] = {id=776,en="Yagudo Coopkeeper",ja="ヤグード　クップキーパー"},
    [777] = {id=777,en="Gigasplosion Expert",ja="ギガスプロード　エキスパート"},
    [778] = {id=778,en="Brother-in-arms",ja="ブラザーインアームズ"},
    [779] = {id=779,en="Antica Hunter",ja="アンティカ　ハンター"},
    [780] = {id=780,en="Amphibian Adulterator",ja="アンフィ　アダルタレイター"},
    [781] = {id=781,en="Tonberry Toppler",ja="トンベリ　トップラー"},
    [782] = {id=782,en="Bloodline Corrupter",ja="ブラッドライン　コラプター"},
    [783] = {id=783,en="Kumhau Roaster",ja="クムハウ　ロースター"},
    [784] = {id=784,en="Brilliance Manifest",ja="ブリリアンス　マニフェスト"},
    [785] = {id=785,en="Quieter of Ancient Thoughts",ja="エンシェントソート　クワイエター"},
    [786] = {id=786,en="Ark Hume Humiliator",ja="アークヒューム　ヒューミリアター"},
    [787] = {id=787,en="Ark Elvaan Eviscerator",ja="アークエルヴァーン　エビサレイター"},
    [788] = {id=788,en="Ark Mithra Maligner",ja="アークミスラ　マライナー"},
    [789] = {id=789,en="Ark Tarutaru Trouncer",ja="アークタルタル　トラウンサー"},
    [790] = {id=790,en="Ark Galka Gouger",ja="アークガルカ　ガウジャー"},
    [791] = {id=791,en="Pentarch Pacifier",ja="ペンターク　パシファイアー"},
    [792] = {id=792,en="Dream Distiller",ja="ドリーム　デスティラー"},
    [793] = {id=793,en="Ra'Kaznar Exemplar",ja="ラ・カザナル　エグゼンプラー"},
    [794] = {id=794,en="Utkux Peltburner",ja="アットクックス　ペルトバーナー"},
    [795] = {id=795,en="Cailimh Plumageplucker",ja="カイルイム　プルメッジプラッカー"},
    [796] = {id=796,en="Wopket Trunksplitter",ja="ウォップケット　トランクスプリッター"},
    [797] = {id=797,en="Ouryu Obfuscator",ja="オウリュウ　オブフスケイター"},
    [798] = {id=798,en="Unwavering Blaze",ja="アンウェーヴ　ブレイズ"},
    [799] = {id=799,en="Lancelord Divester",ja="ランスロード　ディベスター"},
    [800] = {id=800,en="Gessho Pinioner",ja="ゲッショー　ピニオナー"},
    [801] = {id=801,en="Sin Purger",ja="シン　パージャー"},
    [802] = {id=802,en="Adumbration Disperser",ja="アダンブレイション　デスパーサー"},
    [803] = {id=803,en="Queller of Otherworldly Gales",ja="ゲール　クウェラー"},
    [804] = {id=804,en="Blaze Marshaller",ja="ブレイズ　マーシャラー"},
    [805] = {id=805,en="Penitentes Blaster",ja="ペニテンテズ　ブラスター"},
    [806] = {id=806,en="Sirocco Tamer",ja="シロッコ　テイマー"},
    [807] = {id=807,en="Suchian Feller",ja="スキアン　フェラー"},
    [808] = {id=808,en="Ombifid Slayer",ja="オンビフィッド　スレイヤー"},
    [809] = {id=809,en="Nilotican Decimator",ja="ニロチカン　デシメーター"},
    [810] = {id=810,en="Illuminator of the 1st Walk",ja="第1ウォークのイルミネーター"},
    [811] = {id=811,en="Illuminator of the 2nd Walk",ja="第2ウォークのイルミネーター"},
    [812] = {id=812,en="Illuminator of the 3rd Walk",ja="第3ウォークのイルミネーター"},
    [813] = {id=813,en="Illuminator of the 4th Walk",ja="第4ウォークのイルミネーター"},
    [814] = {id=814,en="Illuminator of the 5th Walk",ja="第5ウォークのイルミネーター"},
    [815] = {id=815,en="Illuminator of the 6th Walk",ja="第6ウォークのイルミネーター"},
    [816] = {id=816,en="Illuminator of the 7th Walk",ja="第7ウォークのイルミネーター"},
    [817] = {id=817,en="Illuminator of the 8th Walk",ja="第8ウォークのイルミネーター"},
    [818] = {id=818,en="Illuminator of the 9th Walk",ja="第9ウォークのイルミネーター"},
    [819] = {id=819,en="Illuminator of the 10th Walk",ja="第10ウォークのイルミネーター"},
    [820] = {id=820,en="Illuminator of the 11th Walk",ja="第11ウォークのイルミネーター"},
    [821] = {id=821,en="Illuminator of the 12th Walk",ja="第12ウォークのイルミネーター"},
    [822] = {id=822,en="Illuminator of the 13th Walk",ja="第13ウォークのイルミネーター"},
    [823] = {id=823,en="Illuminator of the 14th Walk",ja="第14ウォークのイルミネーター"},
    [824] = {id=824,en="Illuminator of the 15th Walk",ja="第15ウォークのイルミネーター"},
    [825] = {id=825,en="Lithosphere Annihilator",ja="リソスフィア　アナイアレーター"},
    [826] = {id=826,en="Fulmination Disruptor",ja="フルミネーション　ディスラプター"},
    [827] = {id=827,en="Bore Repulsor",ja="ボア　リパルサー"},
    [828] = {id=828,en="Palloritus Punisher",ja="パロリタス　パニシャー"},
    [829] = {id=829,en="Putraxia Pulverizer",ja="ピュトラクシア　パルバライザー"},
    [830] = {id=830,en="Rancibus Ravager",ja="ランシバス　ラバジャー"},
    [831] = {id=831,en="Alluvion Assailant",ja="アルビオン　アセーラント"},
    [832] = {id=832,en="Perfidien Paindealer",ja="パフィディアン　ペインディーラー"},
    [833] = {id=833,en="Plouton Pincer",ja="プルートン　ピンサー"},
    [834] = {id=834,en="Fleetstalker Fileter",ja="フリートストーカー　フィレーヤー"},
    [835] = {id=835,en="Shockmaw Subjugator",ja="ショックモー　サブジュゲーター"},
    [836] = {id=836,en="Geodancer",ja="見習い風水士"},
    [837] = {id=837,en="Runic Engraver",ja="ルーンを刻みし者"},
    [838] = {id=838,en="Apprentice Tarutaru Sauce Manager",ja="タルタル★ソース・マネージャー見習い"},
    [839] = {id=839,en="Vegetable Revolutionary",ja="ベジタブルレボリューションヘルパー"},
    [840] = {id=840,en="Friend to Gluttons",ja="食いしん坊の友"},
    [841] = {id=841,en="Waypoint Warrior",ja="シャルルのお気に入り"},
    [842] = {id=842,en="Ulbukan Stalwart",ja="混沌への抵抗者"},
    [843] = {id=843,en="Toxin Tussler",ja="どくどくざえもん"},
    [844] = {id=844,en="Spiritual★Star",ja="万象の★地星"},
    [845] = {id=845,en="Stippling★Star",ja="刻印の★剣星"},
    [846] = {id=846,en="Geomancipator",ja="自然の理解者"},
    [847] = {id=847,en="Trialed-and-True Runeist",ja="理の執行者"},
    [848] = {id=848,en="Queen's Confidante",ja="女王の信頼を得し者"},
    [849] = {id=849,en="Princess's Partisan",ja="若姫さまの守り手"},
    [850] = {id=850,en="Potation Pathfinder",ja="ドリンクエクスプローラー"},
    [851] = {id=851,en="Storied Geomancer",ja="深淵なる大風水士"},
    [852] = {id=852,en="Ultimate Runeist",ja="灼然なる大魔導剣士"},
    [853] = {id=853,en="Mog Garden Seedling",ja="モグガーデンのタマゴ"},
    [854] = {id=854,en="Kit Empathizer",ja="にぅにぅオーナー"},
    [855] = {id=855,en="Jingly Dangler",ja="ちゃりちゃりオーナー"},
    [856] = {id=856,en="Mole Manipulator",ja="アニキのオーナー"},
    [857] = {id=857,en="Agrarian Novice",ja="農耕初心者"},
    [858] = {id=858,en="Agrarian Initiate",ja="農耕中級者"},
    [859] = {id=859,en="Agrarian Professional",ja="農耕上級者"},
    [860] = {id=860,en="Agrarian Virtuoso",ja="農耕の達人"},
    [861] = {id=861,en="Agrarian Tutelar",ja="農耕の超人"},
    [862] = {id=862,en="Weed Praetor",ja="草木の守り手"},
    [863] = {id=863,en="Tree Praetor",ja="樹木の守り手"},
    [864] = {id=864,en="Thicket Praetor",ja="林の守り手"},
    [865] = {id=865,en="Forest Praetor",ja="森の守り手"},
    [866] = {id=866,en="Jungle Praetor",ja="ジャングルの守り手"},
    [867] = {id=867,en="Copper Mattock",ja="カッパーマトック"},
    [868] = {id=868,en="Silver Mattock",ja="シルバーマトック"},
    [869] = {id=869,en="Mythril Mattock",ja="ミスリルマトック"},
    [870] = {id=870,en="Gold Mattock",ja="ゴールドマトック"},
    [871] = {id=871,en="Adamanttock",ja="アダマンマトック"},
    [872] = {id=872,en="Puddle Patron",ja="水溜まり師匠"},
    [873] = {id=873,en="Swamp Savant",ja="沼師匠"},
    [874] = {id=874,en="Pond Preceptor",ja="池師匠"},
    [875] = {id=875,en="River Regent",ja="渓流師匠"},
    [876] = {id=876,en="Monke-Onke Master",ja="モンケオンケ師匠"},
    [877] = {id=877,en="Sardineophyte",ja="サーディンちゃん"},
    [878] = {id=878,en="Calamareeler",ja="カラマリちゃん"},
    [879] = {id=879,en="Octopotentate",ja="オクトパちゃん"},
    [880] = {id=880,en="Giant Squimperator",ja="スキッドちゃん"},
    [881] = {id=881,en="Leviauthority",ja="リヴァイアちゃん"},
    [882] = {id=882,en="Novice Nurseryman",ja="園丁"},
    [883] = {id=883,en="Lesser Landscaper",ja="主任庭師"},
    [884] = {id=884,en="Greater Gardener",ja="上級庭師"},
    [885] = {id=885,en="Honored Horticulturist",ja="宮廷庭師"},
    [886] = {id=886,en="Mog Gardener",ja="モグガーデナー"},
    [887] = {id=887,en="Brygidesque Manager",ja="ブリジッド系マネージャー見習い"},
    [888] = {id=888,en="Vegetable Evolutionary",ja="ベジタブルエボリューションヘルパー"},
    [889] = {id=889,en="Blade Enthusiast",ja="魔導マニア"},
    [890] = {id=890,en="Runic Emissary",ja="ルーン宅配人"},
    [891] = {id=891,en="Maester of Maddening",ja="焦らしマイスター"},
    [892] = {id=892,en="Sunshine Cadet",ja="雲飛ばす東風"},
    [893] = {id=893,en="Quartet Captivator",ja="クワッどコア"},
    [894] = {id=894,en="The Trustworthy",ja="信頼・親愛・友情を抱く者"},
    [895] = {id=895,en="The Lovelorn",ja="ラブラブウォッチャー"},
    [896] = {id=896,en="Inventor Extraordinaire",ja="INV.ワークスツカイッパー"},
    [897] = {id=897,en="Boomy and Busty",ja="お遊戯王"},
    [898] = {id=898,en="Weatherer of Brumal Climes",ja="絶零の開拓者"},
    [899] = {id=899,en="White Knight",ja="姫を救いし勇者"},
    [900] = {id=900,en="Light of Dawn",ja="大いなる暁の継承者"},
    [901] = {id=901,en="Observer of Fateful Cubes",ja="一天地六の観測者"},
    [902] = {id=902,en="Knower of Untruths",ja="無知なる知者"},
    [903] = {id=903,en="Ulbukan Understudy",ja="ウルブカの守護者見習い"},
    [904] = {id=904,en="Keeper of Ulbuka",ja="ウルブカの守護者"},
    [905] = {id=905,en="Radiance of Daybreak",ja="暁の光"},
    [906] = {id=906,en="Wibbly Wobbly Woozy Warrior",ja="あばばばヒーラー"},
    [907] = {id=907,en="Heir of Eternity",ja="大いなる時の継承者"},
    [908] = {id=908,en="Prospective Pamperer",ja="初級なでなで士"},
    [909] = {id=909,en="Novice Nuzzler",ja="下級なでなで士"},
    [910] = {id=910,en="Serious Snuggler",ja="上級なでなで士"},
    [911] = {id=911,en="Cultivated Coddler",ja="特級なでなで士"},
    [912] = {id=912,en="Respected Ruffler",ja="なでなで魔神"},
    [913] = {id=913,en="Dung Disseminator",ja="生き物係"},
    [914] = {id=914,en="Fauna Feeder",ja="牧童"},
    [915] = {id=915,en="Confident Caretaker",ja="牧人"},
    [916] = {id=916,en="Glorious Groomer",ja="牧場主"},
    [917] = {id=917,en="Transcendental Tamer",ja="牧畜マスター"},
    [918] = {id=918,en="Bond-building Breeder",ja="心つながるモンスター"},
    [919] = {id=919,en="Clumsy Cleaver",ja="解剖学生"},
    [920] = {id=920,en="Disciplined Dissector",ja="解剖術士"},
    [921] = {id=921,en="Established Examiner",ja="解剖マスター"},
    [922] = {id=922,en="Sublime Slicer",ja="命をかける飼育士"},
    [923] = {id=923,en="Lifter of Spirits",ja="悲嘆の淵の救済者"},
    [924] = {id=924,en="Shedder of Harlequin Tears",ja="ゲームの勝者"},
    [925] = {id=925,en="Hope for the Future",ja="暁の輝き"},
    [926] = {id=926,en="Thousand-Year Traveler",ja="一千年の旅人"},
    [927] = {id=927,en="Vanquisher of Ashrakk",ja="怪霊を討滅せし者"},
    [928] = {id=928,en="Vanquisher of Dhokmak",ja="変妖を討滅せし者"},
    [929] = {id=929,en="Protected by Ulbukan Spirits",ja="英霊の加護ありし者"},
    [930] = {id=930,en="Receiver of Sigils",ja="聖痕の受難者"},
    [931] = {id=931,en="Destroyer of Hades",ja="冥王を討ちし者"},
    [932] = {id=932,en="Bringer of the Dawn",ja="暁の先導者"},
    [933] = {id=933,en="The One True Pioneer",ja="アドゥリンの真なる開拓者"},
    [934] = {id=934,en="Bringer of Hope",ja="希望の先導者"},
    [935] = {id=935,en="Good Dew-er",ja="アドゥリンの露騎士候補"},
    [936] = {id=936,en="Lifecycler",ja="森羅"},
    [937] = {id=937,en="Sword Saint",ja="剣聖"},
    [938] = {id=938,en="The Fated",ja="運命を知った者"},
    [939] = {id=939,en="Protector of the Sacred City",ja="アドゥリンを守りし者"},
    [940] = {id=940,en="Urmahlullu Usurper",ja="ウルマフール　ウサーパー"},
    [941] = {id=941,en="Blazewing Berater",ja="ブレイズウィング　ビレーター"},
    [942] = {id=942,en="Coven Collapser",ja="カヴン　カラプサー"},
    [943] = {id=943,en="Pazuzu Perplexer",ja="パズズ　パプレックサー"},
    [944] = {id=944,en="Wrathare Waxer",ja="ラースヘア　ワックサー"},
    [945] = {id=945,en="Lupine Liquidator",ja="ルーパイン　リクィデーター"},
    [946] = {id=946,en="Ruby Repulser",ja="ルビー　リパルサー"},
    [947] = {id=947,en="Devil's Demise",ja="デヴィル　ディマイズ"},
    [948] = {id=948,en="Custodian of Ulbuka",ja="カストーディアン　オブ　ウルブカ"},
    [949] = {id=949,en="Azi Dahaka Annihilator",ja="アジダハーカ　アナイアレーター"},
    [950] = {id=950,en="Naga Raja Nullifier",ja="ナーガラージャ　ナリファイヤー"},
    [951] = {id=951,en="Quetzalcoatl Plucker",ja="ケツァルコアトル　プラッカー"},
    [952] = {id=952,en="Pakecet Pacifier",ja="パキケト　パシファイヤー"},
    [953] = {id=953,en="Duke Vepar Vanquisher",ja="デュークヴェパー　ヴァンキシャー"},
    [954] = {id=954,en="Vir'ava Vegetator",ja="ヴィラーヴァ　ヴェジテーター"},
    [955] = {id=955,en="Byakko Tamer",ja="ビャッコ　テイマー"},
    [956] = {id=956,en="Genbu Cracker",ja="ゲンブ　クラッカー"},
    [957] = {id=957,en="Seiryu Clipper",ja="セイリュウ　クイッパー"},
    [958] = {id=958,en="Suzaku Plucker",ja="スザク　プラッカー"},
    [959] = {id=959,en="Kirin Dismantler",ja="キリン　ディスマンテラー"},
    [960] = {id=960,en="Vanquisher of Apathy",ja="無知を消し去るもの"},
    [961] = {id=961,en="Vanquisher of Cowardice",ja="怯懦を消し去るもの"},
    [962] = {id=962,en="Vanquisher of Envy",ja="嫉妬を消し去るもの"},
    [963] = {id=963,en="Vanquisher of Arrogance",ja="驕慢を消し去るもの"},
    [964] = {id=964,en="Vanquisher of Rage",ja="憎悪を消し去るもの"},
    [965] = {id=965,en="Purger of the Warder",ja="番人を打ち破ったもの"},
    [966] = {id=966,en="Conquerer of Fear",ja="コンカラー　オブ　フィアー"},
    [967] = {id=967,en="Dawn's Delight",ja="ドーン　ディライト"},
    [968] = {id=968,en="Maju Mauler",ja="マジュー　モーラー"},
    [969] = {id=969,en="Yakshi Yanker",ja="ヤクシー　ヤンカー"},
    [970] = {id=970,en="Neak Nullifier",ja="ニーク　ナリファイア"},
    [971] = {id=971,en="Teles Terrifier",ja="テレス　リペラー"},
    [972] = {id=972,en="Assistant Extraordinaire",ja="最高の助手"},
    [973] = {id=973,en="Exalted Fisherman",ja="釣神"},
    [974] = {id=974,en="Sauce Supreme",ja="タルタル★ソース・いっぱしマネージャー"},
    [975] = {id=975,en="Fish Whisperer",ja="一竿入魂の太公望"},
    [976] = {id=976,en="Abyssal Purveyor",ja="深淵を覗く者"},
    [977] = {id=977,en="Banisher of the Profane",ja="享楽と悪意を退けし者"},
    [978] = {id=978,en="Spirit Seeker",ja="魂の眼を持つ者"},
    [979] = {id=979,en="One-Eyed Jack",ja="ピュラクモンの真実を知る者"},
    [980] = {id=980,en="Curator Culler",ja="キュレーター　カラー"},
    [981] = {id=981,en="Master Centurion",ja="ファイターマスター"},
    [982] = {id=982,en="Master Brawler",ja="テンプルマスター"},
    [983] = {id=983,en="Master Healer",ja="ヒーラーマスター"},
    [984] = {id=984,en="Master Wizard",ja="ウィザードマスター"},
    [985] = {id=985,en="Master Warlock",ja="ワーロックマスター"},
    [986] = {id=986,en="Master Rogue",ja="ローグマスター"},
    [987] = {id=987,en="Master Templar",ja="ガラントマスター"},
    [988] = {id=988,en="Master Soulstealer",ja="カオスマスター"},
    [989] = {id=989,en="Master Tamer",ja="ビーストマスター"},
    [990] = {id=990,en="Master Lyricist",ja="コラルマスター"},
    [991] = {id=991,en="Master Hunter",ja="ハンターマスター"},
    [992] = {id=992,en="Master Mononofu",ja="モノノフマスター"},
    [993] = {id=993,en="Master Shinobi",ja="シノビマスター"},
    [994] = {id=994,en="Master Hussar",ja="ドラケンマスター"},
    [995] = {id=995,en="Master Evoker",ja="エボカーマスター"},
    [996] = {id=996,en="Master Magus",ja="メガスマスター"},
    [997] = {id=997,en="Master Privateer",ja="コルセアマスター"},
    [998] = {id=998,en="Master Puppeteer",ja="パペトリマスター"},
    [999] = {id=999,en="Master Headliner",ja="ダンサーマスター"},
    [1000] = {id=1000,en="Master Academic",ja="スカラーマスター"},
    [1001] = {id=1001,en="Master Naturalist",ja="ジオマスター"},
    [1002] = {id=1002,en="Master Runeist",ja="ルーニストマスター"},
    [1003] = {id=1003,en="Zerde Zapper",ja="ゼルデ　ザッパー"},
    [1004] = {id=1004,en="Vinipata Vanquisher",ja="ヴィニパタ　ヴァンクィシャー"},
    [1005] = {id=1005,en="Schah Scraper",ja="シャー　スクレーパー"},
    [1006] = {id=1006,en="Albumen Aggrivator",ja="アルブメン　アグリヴェーター"},
    [1007] = {id=1007,en="Onychophora Obliterator",ja="オニコフォラ　オブリテレーター"},
    [1008] = {id=1008,en="Erinys Engulfer",ja="エリニス　エンガルファー"},
    [1009] = {id=1009,en="Herald of a New Age",ja="ヘラルド　オブ　ア　ニュー　エイジ"},
    [1010] = {id=1010,en="Preventer of the Second Coming",ja="再臨を食い止めし者"},
    [1011] = {id=1011,en="Lux Ex Tenebris",ja="ルックス・エクス・テネブリス"},
    [1012] = {id=1012,en="The Triumphant",ja="トライアンファント"},
    [1044] = {id=1044,en="Vegetable Hero",ja="カリカリ救世主"},
    [1045] = {id=1045,en="Contributer from the Shadows",ja="陰の貢献者なのん"},
    [1046] = {id=1046,en="The Decider",ja="裁定者"},
    [1047] = {id=1047,en="The Ascended",ja="神となりし者"},
    [1048] = {id=1048,en="The Savior of Vana'diel",ja="ヴァナ・ディールの救世主"},
    [1049] = {id=1049,en="Blessed by the Avatars",ja="大いなる力の継承者"},
    [1050] = {id=1050,en="Seer of Songs",ja="星唄に乗せて歩み続ける者"},
    [1051] = {id=1051,en="The Eternal Wind",ja="悠久の風"},
    [1116] = {id=1116,en="Raptor Wrangler",ja="爆速ラプトルライダー"},
    [1117] = {id=1117,en="Gardener for the Ages",ja="疾走ガーデンライダー"},
    [1118] = {id=1118,en="Lagoon Explorer",ja="伝説ラグーンライダー"},
}, {"id", "en", "ja"}

--[[
Copyright © 2013-2016, Windower
All rights reserved.

Redistribution and use in source and binary forms, with or without modification, are permitted provided that the following conditions are met:

    * Redistributions of source code must retain the above copyright notice, this list of conditions and the following disclaimer.
    * Redistributions in binary form must reproduce the above copyright notice, this list of conditions and the following disclaimer in the documentation and/or other materials provided with the distribution.
    * Neither the name of Windower nor the names of its contributors may be used to endorse or promote products derived from this software without specific prior written permission.

THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL Windower BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
]]
